import type {
  CreatorProfile,
  VaultAsset,
  Story,
  Article,
  Collection,
  CertificationEvent,
  BuyerAccount,
  DirectOffer,
  Assignment,
  Settlement,
  Lightbox,
  Transaction,
  SocialCounts,
  Comment,
  CommentAuthor,
  Conversation,
  DirectMessage,
  FollowState,
} from './types'

// ── Creator Profile (Sarah Chen from onboarding) ──

export const mockCreatorProfile: CreatorProfile = {
  username: 'sarahchen',
  displayName: 'Sarah Chen',
  professionalTitle: 'Senior Correspondent, Asia Pacific',
  locationBase: 'Hong Kong, China',
  websiteUrl: 'https://sarahchen.press',
  biography:
    'Award-winning journalist covering conflict, climate, and technology across Asia Pacific for over 12 years. Previously with Reuters and the South China Morning Post.',
  avatarUrl: '/assets/avatars/pexels-anete-lusina-4793183.jpg',
  trustTier: 'standard',
  trustBadge: 'verified',
  verificationStatus: 'verified',
  lastVerifiedAt: '2026-03-15T10:30:00Z',
  foundingMember: true,
  coverageAreas: ['China', 'Hong Kong', 'Taiwan', 'Southeast Asia'],
  specialisations: ['Conflict Reporting', 'Climate', 'Technology', 'Politics'],
  mediaAffiliations: ['Reuters', 'South China Morning Post', 'Foreign Policy'],
  pressAccreditations: [
    "Foreign Correspondents' Club of China",
    'Hong Kong Journalists Association',
  ],
  publishedIn: [
    'Reuters',
    'South China Morning Post',
    'Foreign Policy',
    'The Guardian',
  ],
  skills: [
    'Long-form Reporting',
    'Photojournalism',
    'Video Production',
    'Data Journalism',
  ],
  alsoMeLinks: [
    'https://linkedin.com/in/sarahchen-journalist',
    'https://twitter.com/sarahchenreports',
    'https://instagram.com/sarahchenreports',
    'https://facebook.com/sarahchen.journalist',
    'https://flickr.com/photos/sarahchen',
    'https://youtube.com/@sarahchenreports',
  ],
  stats: {
    totalAssets: 53,
    totalStories: 3,
    totalArticles: 3,
    totalCollections: 2,
  },
  licensing: {
    available: true,
    licenceTypes: ['editorial', 'commercial', 'broadcast'],
    priceBandLabel: '$$',
  },
}

// ── Vault Assets ──

export const mockVaultAssets: VaultAsset[] = [
  {
    id: 'asset-001',
    title: 'Hong Kong protest, tear gas deployment, Mong Kok',
    description: 'Tear gas canisters fired at protestors near Mong Kok MTR station.',
    format: 'photo',
    thumbnailUrl: '/assets/11862_large.jpeg',
    privacy: 'PUBLIC',
    declarationState: 'fully_validated',
    publication: 'PUBLISHED',
    uploadedAt: '2026-03-16T08:12:00Z',
    certifiedAt: '2026-03-16T08:14:22Z',
    certificationHash: 'fcs-a7b3e9f2',
    fileSize: '14.2 MB',
    storyId: 'story-003',
    creatorPrice: 15000,
    enabledLicences: ['editorial', 'broadcast'],
    exclusiveLock: null,
  },
  {
    id: 'asset-002',
    title: 'Climate summit panel, COP31 Singapore',
    description: 'Panel discussion at COP31 climate summit in Singapore.',
    format: 'photo',
    thumbnailUrl: '/assets/8294_large.jpeg',
    privacy: 'PUBLIC',
    declarationState: 'fully_validated',
    publication: 'PUBLISHED',
    uploadedAt: '2026-03-17T14:30:00Z',
    certifiedAt: '2026-03-17T14:32:11Z',
    certificationHash: 'fcs-c4d8e1a0',
    fileSize: '11.8 MB',
    storyId: 'story-001',
    creatorPrice: 12000,
    enabledLicences: ['editorial', 'commercial'],
    exclusiveLock: null,
  },
  {
    id: 'asset-003',
    title: 'Interview transcript, Minister Li Wei',
    description: 'Full transcript of exclusive interview with Minister Li Wei on trade policy.',
    format: 'text',
    thumbnailUrl: '/assets/8939_large.jpeg',
    privacy: 'PRIVATE',
    declarationState: 'fully_validated',
    publication: 'DRAFT',
    uploadedAt: '2026-03-18T09:00:00Z',
    certifiedAt: '2026-03-18T09:02:45Z',
    certificationHash: 'fcs-e2f5a8b1',
    fileSize: '240 KB',
    storyId: 'story-002',
    creatorPrice: 25000,
    enabledLicences: ['editorial'],
    exclusiveLock: null,
  },
  {
    id: 'asset-004',
    title: 'Typhoon aftermath, Cebu coast drone footage',
    description: 'Aerial drone footage of typhoon damage along the Cebu coastline.',
    format: 'video',
    thumbnailUrl: '/assets/8654_large.jpeg',
    videoUrl: '/assets/videos/cloud-timelapse.mp4',
    privacy: 'PUBLIC',
    declarationState: 'provenance_pending',
    publication: 'PUBLISHED',
    uploadedAt: '2026-03-19T16:45:00Z',
    certifiedAt: '2026-03-19T16:48:30Z',
    certificationHash: 'fcs-b9c2d4e7',
    fileSize: '890 MB',
    storyId: 'story-001',
    creatorPrice: 35000,
    enabledLicences: ['editorial', 'broadcast', 'digital'],
    exclusiveLock: null,
  },
  {
    id: 'asset-005',
    title: 'Shenzhen tech district, factory floor',
    description: 'Inside a semiconductor fabrication facility in Shenzhen technology district.',
    format: 'photo',
    thumbnailUrl: '/assets/12087_large.jpeg',
    privacy: 'PUBLIC',
    declarationState: 'provenance_pending',
    publication: 'DRAFT',
    uploadedAt: '2026-03-20T11:20:00Z',
    certifiedAt: null,
    certificationHash: null,
    fileSize: '16.1 MB',
    storyId: 'story-002',
    creatorPrice: 10000,
    enabledLicences: ['editorial'],
    exclusiveLock: null,
  },
  {
    id: 'asset-006',
    title: 'Taiwan strait patrol, naval vessels',
    description: 'Naval patrol vessels in the Taiwan strait during routine exercises.',
    format: 'photo',
    thumbnailUrl: '/assets/13977_large.jpeg',
    privacy: 'RESTRICTED',
    declarationState: 'fully_validated',
    publication: 'DRAFT',
    uploadedAt: '2026-03-21T06:30:00Z',
    certifiedAt: '2026-03-21T06:33:12Z',
    certificationHash: 'fcs-d1e4f7a3',
    fileSize: '18.4 MB',
    storyId: null,
    creatorPrice: 20000,
    enabledLicences: ['editorial'],
    exclusiveLock: null,
  },
  {
    id: 'asset-007',
    title: 'Audio recording, press briefing, Beijing',
    description: 'Audio recording of a government press briefing in Beijing.',
    format: 'audio',
    thumbnailUrl: null,
    audioUrl: '/assets/audio/digital-age-vocal.wav',
    privacy: 'PUBLIC',
    declarationState: 'fully_validated',
    publication: 'PUBLISHED',
    uploadedAt: '2026-03-22T13:00:00Z',
    certifiedAt: null,
    certificationHash: null,
    fileSize: '45 MB',
    storyId: null,
    creatorPrice: null,
    enabledLicences: [],
    exclusiveLock: null,
  },
  {
    id: 'asset-008',
    title: 'Refugee camp documentation, Mae Sot border',
    description: 'Conditions at the Mae Sot refugee camp on the Thailand-Myanmar border.',
    format: 'photo',
    thumbnailUrl: '/assets/13937_large.jpeg',
    privacy: 'PUBLIC',
    declarationState: 'fully_validated',
    publication: 'PUBLISHED',
    uploadedAt: '2026-03-23T07:15:00Z',
    certifiedAt: '2026-03-23T07:18:00Z',
    certificationHash: 'fcs-f3a6b9c2',
    fileSize: '12.7 MB',
    storyId: 'story-003',
    creatorPrice: 18000,
    enabledLicences: ['editorial', 'print', 'digital'],
    exclusiveLock: null,
  },
  {
    id: 'asset-009',
    title: 'Southeast Asia climate risk zones',
    description: 'Data visualisation mapping flood and storm risk across Southeast Asian coastal cities.',
    format: 'infographic',
    thumbnailUrl: '/assets/illustrations/modern-infographic.jpg',
    illustrationUrl: '/assets/illustrations/modern-infographic.jpg',
    privacy: 'PUBLIC',
    declarationState: 'provenance_pending',
    publication: 'PUBLISHED',
    uploadedAt: '2026-03-24T10:00:00Z',
    certifiedAt: '2026-03-24T10:03:00Z',
    certificationHash: 'fcs-g4h7i0j3',
    fileSize: '8.2 MB',
    storyId: 'story-001',
    creatorPrice: 8000,
    enabledLicences: ['editorial', 'digital', 'web'],
    exclusiveLock: null,
  },
  {
    id: 'asset-010',
    title: 'Mekong Delta displacement routes',
    description: 'Vector-format map showing internal displacement routes from the Mekong Delta.',
    format: 'vector',
    thumbnailUrl: '/assets/vectors/silhouette-vectors.svg',
    illustrationUrl: '/assets/vectors/silhouette-vectors.svg',
    privacy: 'PUBLIC',
    declarationState: 'fully_validated',
    publication: 'PUBLISHED',
    uploadedAt: '2026-03-25T08:00:00Z',
    certifiedAt: '2026-03-25T08:02:00Z',
    certificationHash: 'fcs-k5l8m1n4',
    fileSize: '2.1 MB',
    storyId: 'story-001',
    creatorPrice: 6000,
    enabledLicences: ['editorial', 'print'],
    exclusiveLock: null,
  },
  {
    id: 'asset-011',
    title: 'Indigenous ceremony, Xingu territory',
    description: 'Young warriors in formation during ceremonial gathering in Xingu indigenous territory.',
    format: 'photo',
    thumbnailUrl: '/assets/6245_large.jpeg',
    privacy: 'PUBLIC',
    declarationState: 'fully_validated',
    publication: 'PUBLISHED',
    uploadedAt: '2026-03-10T06:00:00Z',
    certifiedAt: '2026-03-10T06:03:00Z',
    certificationHash: 'fcs-m2n5o8p1',
    fileSize: '18.6 MB',
    storyId: 'story-003',
    creatorPrice: 22000,
    enabledLicences: ['editorial', 'print'],
    exclusiveLock: null,
  },
  {
    id: 'asset-012',
    title: 'Protest burning, Lima intersection',
    description: 'Demonstrators burn materials at a major intersection during unrest in Lima.',
    format: 'photo',
    thumbnailUrl: '/assets/12948_large.jpeg',
    privacy: 'PUBLIC',
    declarationState: 'fully_validated',
    publication: 'PUBLISHED',
    uploadedAt: '2026-03-11T09:30:00Z',
    certifiedAt: '2026-03-11T09:32:00Z',
    certificationHash: 'fcs-q3r6s9t2',
    fileSize: '15.3 MB',
    storyId: 'story-003',
    creatorPrice: 16000,
    enabledLicences: ['editorial', 'broadcast'],
    exclusiveLock: null,
  },
  {
    id: 'asset-013',
    title: 'Solidarity march, keffiyeh detail',
    description: 'Demonstrators at solidarity march with peace signs and flags.',
    format: 'photo',
    thumbnailUrl: '/assets/12997_large.jpeg',
    privacy: 'PUBLIC',
    declarationState: 'provenance_pending',
    publication: 'PUBLISHED',
    uploadedAt: '2026-03-12T11:00:00Z',
    certifiedAt: '2026-03-12T11:03:00Z',
    certificationHash: 'fcs-u4v7w0x3',
    fileSize: '13.1 MB',
    storyId: 'story-003',
    creatorPrice: 14000,
    enabledLicences: ['editorial'],
    exclusiveLock: null,
  },
  {
    id: 'asset-014',
    title: 'Capoeira practice, community centre',
    description: 'Youth practicing capoeira at a neighbourhood community centre.',
    format: 'photo',
    thumbnailUrl: '/assets/4398_large.jpeg',
    privacy: 'PUBLIC',
    declarationState: 'fully_validated',
    publication: 'PUBLISHED',
    uploadedAt: '2026-03-05T14:00:00Z',
    certifiedAt: '2026-03-05T14:02:00Z',
    certificationHash: 'fcs-y5z8a1b4',
    fileSize: '11.2 MB',
    storyId: null,
    creatorPrice: 9000,
    enabledLicences: ['editorial', 'digital'],
    exclusiveLock: null,
  },
  {
    id: 'asset-015',
    title: 'Laughter at the window',
    description: 'Couple laughing at their window in rural community.',
    format: 'photo',
    thumbnailUrl: '/assets/3578_large.jpeg',
    privacy: 'PUBLIC',
    declarationState: 'fully_validated',
    publication: 'PUBLISHED',
    uploadedAt: '2026-03-06T07:30:00Z',
    certifiedAt: '2026-03-06T07:32:00Z',
    certificationHash: 'fcs-c2d5e8f1',
    fileSize: '10.8 MB',
    storyId: null,
    creatorPrice: 8500,
    enabledLicences: ['editorial', 'print'],
    exclusiveLock: null,
  },
  {
    id: 'asset-016',
    title: 'Singer at pride stage',
    description: 'Performer on stage with rainbow backdrop at pride celebration.',
    format: 'photo',
    thumbnailUrl: '/assets/12280_large.jpeg',
    privacy: 'PUBLIC',
    declarationState: 'provenance_pending',
    publication: 'PUBLISHED',
    uploadedAt: '2026-03-07T16:00:00Z',
    certifiedAt: '2026-03-07T16:02:00Z',
    certificationHash: 'fcs-g3h6i9j2',
    fileSize: '14.5 MB',
    storyId: null,
    creatorPrice: 11000,
    enabledLicences: ['editorial', 'commercial'],
    exclusiveLock: null,
  },
  {
    id: 'asset-017',
    title: 'Mountain bike jump, Andes',
    description: 'Mountain biker mid-air against Andean peaks.',
    format: 'photo',
    thumbnailUrl: '/assets/12480_large.jpeg',
    privacy: 'PUBLIC',
    declarationState: 'fully_validated',
    publication: 'PUBLISHED',
    uploadedAt: '2026-03-08T10:00:00Z',
    certifiedAt: '2026-03-08T10:02:00Z',
    certificationHash: 'fcs-k4l7m0n3',
    fileSize: '16.9 MB',
    storyId: null,
    creatorPrice: 13000,
    enabledLicences: ['editorial', 'commercial', 'digital'],
    exclusiveLock: null,
  },
  {
    id: 'asset-018',
    title: 'Cotton candy vendor, night market',
    description: 'Street vendor obscured by cotton candy at evening market.',
    format: 'photo',
    thumbnailUrl: '/assets/11847_large.jpeg',
    privacy: 'PUBLIC',
    declarationState: 'fully_validated',
    publication: 'PUBLISHED',
    uploadedAt: '2026-03-09T19:00:00Z',
    certifiedAt: '2026-03-09T19:02:00Z',
    certificationHash: 'fcs-o5p8q1r4',
    fileSize: '9.7 MB',
    storyId: null,
    creatorPrice: 7500,
    enabledLicences: ['editorial'],
    exclusiveLock: null,
  },
  {
    id: 'asset-019',
    title: 'Hmong woman carrying child, Guizhou',
    description: 'Hmong woman in traditional dress carrying infant through village courtyard.',
    format: 'photo',
    thumbnailUrl: '/assets/1282_large.jpeg',
    privacy: 'PUBLIC',
    declarationState: 'fully_validated',
    publication: 'PUBLISHED',
    uploadedAt: '2026-02-28T08:00:00Z',
    certifiedAt: '2026-02-28T08:03:00Z',
    certificationHash: 'fcs-s6t9u2v5',
    fileSize: '13.4 MB',
    storyId: 'story-001',
    creatorPrice: 17000,
    enabledLicences: ['editorial', 'print'],
    exclusiveLock: null,
  },
  {
    id: 'asset-020',
    title: 'Carnival portrait, Copacabana',
    description: 'Two men in costume on Copacabana beach during carnival.',
    format: 'photo',
    thumbnailUrl: '/assets/13139_large.jpeg',
    privacy: 'PUBLIC',
    declarationState: 'provenance_pending',
    publication: 'PUBLISHED',
    uploadedAt: '2026-03-01T12:00:00Z',
    certifiedAt: '2026-03-01T12:03:00Z',
    certificationHash: 'fcs-w7x0y3z6',
    fileSize: '12.0 MB',
    storyId: null,
    creatorPrice: 10000,
    enabledLicences: ['editorial', 'digital'],
    exclusiveLock: null,
  },
  {
    id: 'asset-021',
    title: 'Cholita portrait, La Paz',
    description: 'Close portrait of a cholita at a public gathering in La Paz.',
    format: 'photo',
    thumbnailUrl: '/assets/13911_large.jpeg',
    privacy: 'PUBLIC',
    declarationState: 'fully_validated',
    publication: 'PUBLISHED',
    uploadedAt: '2026-03-02T09:00:00Z',
    certifiedAt: '2026-03-02T09:02:00Z',
    certificationHash: 'fcs-a8b1c4d7',
    fileSize: '11.5 MB',
    storyId: null,
    creatorPrice: 9500,
    enabledLicences: ['editorial', 'print'],
    exclusiveLock: null,
  },
  {
    id: 'asset-022',
    title: 'Jungle bridge crossing, Amazon basin',
    description: 'Motorcyclists crossing a makeshift wooden bridge in the Amazon.',
    format: 'photo',
    thumbnailUrl: '/assets/13933_large.jpeg',
    privacy: 'PUBLIC',
    declarationState: 'fully_validated',
    publication: 'PUBLISHED',
    uploadedAt: '2026-03-03T07:00:00Z',
    certifiedAt: '2026-03-03T07:03:00Z',
    certificationHash: 'fcs-e9f2g5h8',
    fileSize: '17.2 MB',
    storyId: 'story-001',
    creatorPrice: 15000,
    enabledLicences: ['editorial', 'broadcast'],
    exclusiveLock: null,
  },
  {
    id: 'asset-023',
    title: 'Boys in the river, Maranhao',
    description: 'Children swimming and holding a lightbulb in a river in Maranhao.',
    format: 'photo',
    thumbnailUrl: '/assets/10062_large.jpeg',
    privacy: 'PUBLIC',
    declarationState: 'provenance_pending',
    publication: 'PUBLISHED',
    uploadedAt: '2026-03-04T15:00:00Z',
    certifiedAt: '2026-03-04T15:02:00Z',
    certificationHash: 'fcs-i0j3k6l9',
    fileSize: '14.0 MB',
    storyId: 'story-001',
    creatorPrice: 12000,
    enabledLicences: ['editorial'],
    exclusiveLock: null,
  },
  {
    id: 'asset-024',
    title: 'BLM protest signs, White House fence',
    description: 'Protest signs and artwork on the White House perimeter fence.',
    format: 'photo',
    thumbnailUrl: '/assets/2374_large.jpeg',
    privacy: 'PUBLIC',
    declarationState: 'fully_validated',
    publication: 'PUBLISHED',
    uploadedAt: '2026-02-25T10:00:00Z',
    certifiedAt: '2026-02-25T10:03:00Z',
    certificationHash: 'fcs-m1n4o7p0',
    fileSize: '15.8 MB',
    storyId: 'story-003',
    creatorPrice: 19000,
    enabledLicences: ['editorial', 'broadcast', 'digital'],
    exclusiveLock: null,
  },
  {
    id: 'asset-025',
    title: 'Concert stage, white suit performer',
    description: 'Performer in white suit under stage lights at outdoor venue.',
    format: 'photo',
    thumbnailUrl: '/assets/12435_large.jpeg',
    privacy: 'PUBLIC',
    declarationState: 'fully_validated',
    publication: 'PUBLISHED',
    uploadedAt: '2026-02-26T21:00:00Z',
    certifiedAt: '2026-02-26T21:02:00Z',
    certificationHash: 'fcs-q2r5s8t1',
    fileSize: '13.6 MB',
    storyId: null,
    creatorPrice: 11000,
    enabledLicences: ['editorial', 'commercial'],
    exclusiveLock: null,
  },
  {
    id: 'asset-026',
    title: 'Indigenous leader, feathered headdress',
    description: 'Indigenous leader with traditional face paint and feathered headdress at gathering.',
    format: 'photo',
    thumbnailUrl: '/assets/15024_large.jpeg',
    privacy: 'PUBLIC',
    declarationState: 'fully_validated',
    publication: 'PUBLISHED',
    uploadedAt: '2026-02-27T08:00:00Z',
    certifiedAt: '2026-02-27T08:02:00Z',
    certificationHash: 'fcs-u3v6w9x2',
    fileSize: '16.3 MB',
    storyId: 'story-001',
    creatorPrice: 20000,
    enabledLicences: ['editorial', 'print'],
    exclusiveLock: null,
  },
  {
    id: 'asset-027',
    title: 'Huka Huka wrestling, Xingu games',
    description: 'Traditional Huka Huka wrestling match during indigenous games.',
    format: 'photo',
    thumbnailUrl: '/assets/15447_large.jpeg',
    privacy: 'PUBLIC',
    declarationState: 'provenance_pending',
    publication: 'PUBLISHED',
    uploadedAt: '2026-02-20T14:00:00Z',
    certifiedAt: '2026-02-20T14:02:00Z',
    certificationHash: 'fcs-y4z7a0b3',
    fileSize: '17.8 MB',
    storyId: null,
    creatorPrice: 16000,
    enabledLicences: ['editorial', 'broadcast'],
    exclusiveLock: null,
  },
  {
    id: 'asset-028',
    title: 'Ritual anklets, ceremonial dance',
    description: 'Close-up of painted legs and beaded anklets during ceremonial dance.',
    format: 'photo',
    thumbnailUrl: '/assets/15420_large.jpeg',
    privacy: 'PUBLIC',
    declarationState: 'fully_validated',
    publication: 'PUBLISHED',
    uploadedAt: '2026-02-21T09:00:00Z',
    certifiedAt: '2026-02-21T09:02:00Z',
    certificationHash: 'fcs-c5d8e1f4',
    fileSize: '14.7 MB',
    storyId: null,
    creatorPrice: 13000,
    enabledLicences: ['editorial', 'print', 'digital'],
    exclusiveLock: null,
  },
  {
    id: 'asset-029',
    title: 'Pride crowd, Salvador',
    description: 'Crowd at pride parade in Salvador, Bahia.',
    format: 'photo',
    thumbnailUrl: '/assets/14615_large.jpeg',
    privacy: 'PUBLIC',
    declarationState: 'fully_validated',
    publication: 'PUBLISHED',
    uploadedAt: '2026-02-22T16:00:00Z',
    certifiedAt: '2026-02-22T16:03:00Z',
    certificationHash: 'fcs-g6h9i2j5',
    fileSize: '12.4 MB',
    storyId: null,
    creatorPrice: 10000,
    enabledLicences: ['editorial', 'commercial'],
    exclusiveLock: null,
  },
  {
    id: 'asset-030',
    title: 'Indigenous children, village clearing',
    description: 'Two children walking through a village clearing during ceremony.',
    format: 'photo',
    thumbnailUrl: '/assets/14889_large.jpeg',
    privacy: 'PUBLIC',
    declarationState: 'fully_validated',
    publication: 'PUBLISHED',
    uploadedAt: '2026-02-23T06:00:00Z',
    certifiedAt: '2026-02-23T06:02:00Z',
    certificationHash: 'fcs-k7l0m3n6',
    fileSize: '15.1 MB',
    storyId: 'story-001',
    creatorPrice: 14000,
    enabledLicences: ['editorial'],
    exclusiveLock: null,
  },
  {
    id: 'asset-031',
    title: 'Rural life, donkey transport',
    description: 'Man walking alongside a loaded donkey on a village road.',
    format: 'photo',
    thumbnailUrl: '/assets/10033_large.jpeg',
    privacy: 'PUBLIC',
    declarationState: 'provenance_pending',
    publication: 'PUBLISHED',
    uploadedAt: '2026-02-24T11:00:00Z',
    certifiedAt: '2026-02-24T11:02:00Z',
    certificationHash: 'fcs-o8p1q4r7',
    fileSize: '11.9 MB',
    storyId: 'story-001',
    creatorPrice: 8000,
    enabledLicences: ['editorial'],
    exclusiveLock: null,
  },
  {
    id: 'asset-032',
    title: 'Family portrait, Brasilia suburb',
    description: 'Family standing together in front of their home.',
    format: 'photo',
    thumbnailUrl: '/assets/8936_large.jpeg',
    privacy: 'PUBLIC',
    declarationState: 'fully_validated',
    publication: 'DRAFT',
    uploadedAt: '2026-02-18T13:00:00Z',
    certifiedAt: '2026-02-18T13:02:00Z',
    certificationHash: 'fcs-s9t2u5v8',
    fileSize: '10.3 MB',
    storyId: null,
    creatorPrice: 7000,
    enabledLicences: ['editorial'],
    exclusiveLock: null,
  },
  {
    id: 'asset-033',
    title: 'Girl on the beach, Maranhao coast',
    description: 'Young woman on rocky coastline near fishing village.',
    format: 'photo',
    thumbnailUrl: '/assets/10056_large.jpeg',
    privacy: 'PUBLIC',
    declarationState: 'fully_validated',
    publication: 'DRAFT',
    uploadedAt: '2026-02-19T08:00:00Z',
    certifiedAt: '2026-02-19T08:03:00Z',
    certificationHash: 'fcs-w0x3y6z9',
    fileSize: '13.8 MB',
    storyId: 'story-001',
    creatorPrice: 11000,
    enabledLicences: ['editorial', 'print'],
    exclusiveLock: null,
  },
  {
    id: 'asset-034',
    title: 'Apocalypse in New York, Manhattan skyline',
    description: 'Dramatic dystopian footage of New York City under storm clouds.',
    format: 'video',
    thumbnailUrl: '/assets/7944_large.jpeg',
    videoUrl: '/assets/videos/apocalypse-nyc.mp4',
    privacy: 'PUBLIC',
    declarationState: 'fully_validated',
    publication: 'PUBLISHED',
    uploadedAt: '2026-04-01T09:00:00Z',
    certifiedAt: '2026-04-01T09:03:00Z',
    certificationHash: 'fcs-v1a2b3c4',
    fileSize: '28 MB',
    storyId: 'story-001',
    creatorPrice: 45000,
    enabledLicences: ['editorial', 'broadcast', 'digital'],
    exclusiveLock: null,
  },
  {
    id: 'asset-035',
    title: 'Artisan bread making, close-up cut',
    description: 'Close-up footage of freshly baked bread being sliced.',
    format: 'video',
    thumbnailUrl: '/assets/9132_large.jpeg',
    videoUrl: '/assets/videos/bread-cut.mp4',
    privacy: 'PUBLIC',
    declarationState: 'fully_validated',
    publication: 'PUBLISHED',
    uploadedAt: '2026-04-02T11:30:00Z',
    certifiedAt: '2026-04-02T11:32:00Z',
    certificationHash: 'fcs-v2d5e6f7',
    fileSize: '7.5 MB',
    storyId: null,
    creatorPrice: 8000,
    enabledLicences: ['editorial', 'commercial'],
    exclusiveLock: null,
  },
  {
    id: 'asset-036',
    title: 'Market crowd, traditional textile bazaar',
    description: 'Lively crowd browsing colorful clothes in a traditional market.',
    format: 'video',
    thumbnailUrl: '/assets/7608_large.jpeg',
    videoUrl: '/assets/videos/market-crowd.mp4',
    privacy: 'PUBLIC',
    declarationState: 'fully_validated',
    publication: 'PUBLISHED',
    uploadedAt: '2026-04-03T08:15:00Z',
    certifiedAt: '2026-04-03T08:17:00Z',
    certificationHash: 'fcs-v3g8h9i0',
    fileSize: '13 MB',
    storyId: 'story-001',
    creatorPrice: 18000,
    enabledLicences: ['editorial', 'digital'],
    exclusiveLock: null,
  },
  {
    id: 'asset-037',
    title: 'Bass player, underground jazz session',
    description: 'Man playing bass guitar in an intimate underground venue.',
    format: 'video',
    thumbnailUrl: '/assets/7484_large.jpeg',
    videoUrl: '/assets/videos/bass-player.mp4',
    privacy: 'PUBLIC',
    declarationState: 'corroborated',
    publication: 'PUBLISHED',
    uploadedAt: '2026-04-04T20:00:00Z',
    certifiedAt: '2026-04-04T20:02:00Z',
    certificationHash: 'fcs-v4j1k2l3',
    fileSize: '14 MB',
    storyId: null,
    creatorPrice: 12000,
    enabledLicences: ['editorial', 'broadcast'],
    exclusiveLock: null,
  },
  {
    id: 'asset-038',
    title: 'Spaghetti alle vongole, kitchen prep',
    description: 'Preparing spaghetti with clams in a professional kitchen pan.',
    format: 'video',
    thumbnailUrl: '/assets/9241_large.jpeg',
    videoUrl: '/assets/videos/spaghetti-clams.mp4',
    privacy: 'PUBLIC',
    declarationState: 'fully_validated',
    publication: 'PUBLISHED',
    uploadedAt: '2026-04-05T12:00:00Z',
    certifiedAt: '2026-04-05T12:02:00Z',
    certificationHash: 'fcs-v5m4n5o6',
    fileSize: '13 MB',
    storyId: null,
    creatorPrice: 9000,
    enabledLicences: ['editorial', 'commercial'],
    exclusiveLock: null,
  },
  {
    id: 'asset-039',
    title: 'Phone on the beach, smartphone drop',
    description: 'Smartphone falls to the ground on a sandy beach.',
    format: 'video',
    thumbnailUrl: '/assets/9758_large.jpeg',
    videoUrl: '/assets/videos/phone-beach.mp4',
    privacy: 'PUBLIC',
    declarationState: 'corroborated',
    publication: 'PUBLISHED',
    uploadedAt: '2026-04-05T15:30:00Z',
    certifiedAt: '2026-04-05T15:32:00Z',
    certificationHash: 'fcs-v6p7q8r9',
    fileSize: '10 MB',
    storyId: null,
    creatorPrice: 7000,
    enabledLicences: ['editorial', 'digital'],
    exclusiveLock: null,
  },
  {
    id: 'asset-040',
    title: 'Historical letter seal stamping',
    description: 'Close-up of wax seal being stamped on a historical letter.',
    format: 'video',
    thumbnailUrl: '/assets/5066_large.jpeg',
    videoUrl: '/assets/videos/letter-seal.mp4',
    privacy: 'PUBLIC',
    declarationState: 'fully_validated',
    publication: 'PUBLISHED',
    uploadedAt: '2026-04-06T10:00:00Z',
    certifiedAt: '2026-04-06T10:02:00Z',
    certificationHash: 'fcs-v7s0t1u2',
    fileSize: '38 MB',
    storyId: 'story-002',
    creatorPrice: 22000,
    enabledLicences: ['editorial', 'commercial', 'print'],
    exclusiveLock: null,
  },
  {
    id: 'asset-041',
    title: 'Night bridge portrait, neon city',
    description: 'Stylish tattooed man confidently poses on a glowing night bridge.',
    format: 'video',
    thumbnailUrl: '/assets/7756_large.jpeg',
    videoUrl: '/assets/videos/night-bridge.mp4',
    privacy: 'PUBLIC',
    declarationState: 'corroborated',
    publication: 'PUBLISHED',
    uploadedAt: '2026-04-07T22:00:00Z',
    certifiedAt: '2026-04-07T22:02:00Z',
    certificationHash: 'fcs-v8v3w4x5',
    fileSize: '17 MB',
    storyId: null,
    creatorPrice: 15000,
    enabledLicences: ['editorial', 'digital'],
    exclusiveLock: null,
  },
  {
    id: 'asset-042',
    title: 'Monastery ruins, sunlight through stone',
    description: 'Sun shining through the window of old monastery ruins.',
    format: 'video',
    thumbnailUrl: '/assets/3578_large.jpeg',
    videoUrl: '/assets/videos/monastery-ruins.mp4',
    privacy: 'PUBLIC',
    declarationState: 'fully_validated',
    publication: 'PUBLISHED',
    uploadedAt: '2026-04-08T07:00:00Z',
    certifiedAt: '2026-04-08T07:02:00Z',
    certificationHash: 'fcs-v9y6z7a8',
    fileSize: '12 MB',
    storyId: 'story-001',
    creatorPrice: 20000,
    enabledLicences: ['editorial', 'broadcast', 'digital'],
    exclusiveLock: null,
  },
  {
    id: 'asset-043',
    title: 'Venice canals, ancient houses',
    description: 'Gliding through Venice among the ancient houses and waterways.',
    format: 'video',
    thumbnailUrl: '/assets/14715_large.jpeg',
    videoUrl: '/assets/videos/venice-houses.mp4',
    privacy: 'PUBLIC',
    declarationState: 'fully_validated',
    publication: 'PUBLISHED',
    uploadedAt: '2026-04-08T14:00:00Z',
    certifiedAt: '2026-04-08T14:02:00Z',
    certificationHash: 'fcs-w0b1c2d3',
    fileSize: '12 MB',
    storyId: null,
    creatorPrice: 18000,
    enabledLicences: ['editorial', 'commercial', 'digital'],
    exclusiveLock: null,
  },
  {
    id: 'asset-044',
    title: 'Fireball explosion, pyrotechnics',
    description: 'Dramatic fireball explosion captured in slow motion.',
    format: 'video',
    thumbnailUrl: '/assets/8636_large.jpeg',
    videoUrl: '/assets/videos/fireball.mov',
    privacy: 'PUBLIC',
    declarationState: 'provenance_pending',
    publication: 'PUBLISHED',
    uploadedAt: '2026-04-09T06:00:00Z',
    certifiedAt: null,
    certificationHash: null,
    fileSize: '228 MB',
    storyId: null,
    creatorPrice: 50000,
    enabledLicences: ['editorial', 'broadcast', 'commercial'],
    exclusiveLock: null,
  },
  // ── Text Assets ──
  {
    id: 'asset-text-001',
    title: 'Rising Waters: Climate Displacement in the Mekong Delta',
    description: 'Report on families displaced by rising waters in the Mekong Delta, Vietnam.',
    format: 'text',
    thumbnailUrl: null,
    textUrl: '/assets/texts/climate-displacement-mekong.txt',
    textExcerpt: 'The morning mist still clings to the surface of the canal when Nguyen Thi Mai begins loading what remains of her belongings onto a narrow wooden boat. Behind her, the house where she raised three children stands ankle-deep in brackish water, its concrete foundation slowly dissolving into the soft delta mud.',
    privacy: 'PUBLIC',
    declarationState: 'fully_validated',
    publication: 'PUBLISHED',
    uploadedAt: '2026-03-20T09:00:00Z',
    certifiedAt: '2026-03-20T09:02:00Z',
    certificationHash: 'fcs-txt-001',
    fileSize: '12 KB',
    storyId: 'story-002',
    creatorPrice: 8000,
    enabledLicences: ['editorial', 'print', 'digital'],
    exclusiveLock: null,
  },
  {
    id: 'asset-text-002',
    title: 'The Silencing: Press Freedom in Hong Kong',
    description: 'Analysis of press freedom erosion in Hong Kong since 2020.',
    format: 'text',
    thumbnailUrl: null,
    textUrl: '/assets/texts/hong-kong-press-freedom.txt',
    textExcerpt: 'The newsroom on the fourteenth floor of a Wan Chai office tower is quiet in a way that would have been unthinkable three years ago. Desks that once held the chaos of deadline reporting now sit empty, their monitors dark, their chairs pushed neatly against laminate surfaces.',
    privacy: 'PUBLIC',
    declarationState: 'fully_validated',
    publication: 'PUBLISHED',
    uploadedAt: '2026-03-18T14:00:00Z',
    certifiedAt: '2026-03-18T14:03:00Z',
    certificationHash: 'fcs-txt-002',
    fileSize: '15 KB',
    storyId: 'story-003',
    creatorPrice: 12000,
    enabledLicences: ['editorial', 'print', 'digital'],
    exclusiveLock: null,
  },
  {
    id: 'asset-text-003',
    title: 'Under the Canopy: Illegal Logging in Pará State',
    description: 'Investigation into illegal logging operations in Pará state, Brazil.',
    format: 'text',
    thumbnailUrl: null,
    textUrl: '/assets/texts/brazil-amazon-deforestation.txt',
    textExcerpt: 'The satellite imagery tells one story. The ground tells another. From five hundred kilometres above the earth, the clearings in the western Pará rainforest appear as pale geometric scars against an unbroken green canvas.',
    privacy: 'PUBLIC',
    declarationState: 'corroborated',
    publication: 'PUBLISHED',
    uploadedAt: '2026-03-15T11:00:00Z',
    certifiedAt: '2026-03-15T11:04:00Z',
    certificationHash: 'fcs-txt-003',
    fileSize: '14 KB',
    storyId: 'story-001',
    creatorPrice: 10000,
    enabledLicences: ['editorial', 'print'],
    exclusiveLock: null,
  },
  {
    id: 'asset-text-004',
    title: 'Waiting at the Edge: Dispatches from the Evros Border',
    description: 'Dispatch from the Evros border crossing between Greece and Turkey.',
    format: 'text',
    thumbnailUrl: null,
    textUrl: '/assets/texts/greece-refugee-border.txt',
    textExcerpt: 'The wind coming off the Evros river carries the kind of cold that settles into clothing and stays there. On the Greek side of the border, a line of people stretches along a gravel path toward a processing centre that was built for two hundred but now handles six times that number daily.',
    privacy: 'PUBLIC',
    declarationState: 'fully_validated',
    publication: 'PUBLISHED',
    uploadedAt: '2026-03-12T08:30:00Z',
    certifiedAt: '2026-03-12T08:33:00Z',
    certificationHash: 'fcs-txt-004',
    fileSize: '11 KB',
    storyId: 'story-003',
    creatorPrice: 7500,
    enabledLicences: ['editorial', 'digital'],
    exclusiveLock: null,
  },
  {
    id: 'asset-text-005',
    title: 'Breaking Point: Marseille Hospitals Under Heat Siege',
    description: 'Feature on Marseille hospital overwhelm during record February heat.',
    format: 'text',
    thumbnailUrl: null,
    textUrl: '/assets/texts/marseille-heatwave-hospitals.txt',
    textExcerpt: "Dr. Isabelle Fournier has not slept in thirty-one hours. She stands in the corridor of Hôpital Nord, Marseille's largest public hospital, and surveys a scene that belongs more to August than to February.",
    privacy: 'PUBLIC',
    declarationState: 'fully_validated',
    publication: 'PUBLISHED',
    uploadedAt: '2026-03-10T16:00:00Z',
    certifiedAt: '2026-03-10T16:02:00Z',
    certificationHash: 'fcs-txt-005',
    fileSize: '13 KB',
    storyId: 'story-002',
    creatorPrice: 9000,
    enabledLicences: ['editorial', 'print', 'digital'],
    exclusiveLock: null,
  },
  {
    id: 'asset-text-006',
    title: 'Priced Out: Lisbon\'s Housing Affordability Collapse',
    description: 'Report on Lisbon\'s housing crisis and displacement of local residents.',
    format: 'text',
    thumbnailUrl: null,
    textUrl: '/assets/texts/lisbon-housing-crisis.txt',
    textExcerpt: 'Maria do Carmo has lived in the Alfama neighbourhood for sixty-two years. She was born in the apartment above the one she occupies now, a two-room flat with a view of the Tagus that real estate agents have lately begun describing as priceless.',
    privacy: 'PUBLIC',
    declarationState: 'fully_validated',
    publication: 'PUBLISHED',
    uploadedAt: '2026-03-08T10:00:00Z',
    certifiedAt: '2026-03-08T10:01:00Z',
    certificationHash: 'fcs-txt-006',
    fileSize: '10 KB',
    storyId: 'story-003',
    creatorPrice: 8500,
    enabledLicences: ['editorial', 'digital'],
    exclusiveLock: null,
  },
  {
    id: 'asset-text-007',
    title: 'Silicon Shield: Taiwan\'s Chip Sovereignty',
    description: 'Analysis of Taiwan\'s semiconductor industry as geopolitical leverage.',
    format: 'text',
    thumbnailUrl: null,
    textUrl: '/assets/texts/taiwan-chip-sovereignty.txt',
    textExcerpt: 'The facility sits behind three layers of security fencing on the outskirts of Hsinchu, a city that most of the world has never heard of but upon which most of the world depends. Inside, in clean rooms where the air is filtered to a purity that exceeds hospital operating theatres by a factor of a thousand, machines print circuits onto silicon wafers.',
    privacy: 'PUBLIC',
    declarationState: 'fully_validated',
    publication: 'PUBLISHED',
    uploadedAt: '2026-03-05T12:00:00Z',
    certifiedAt: '2026-03-05T12:03:00Z',
    certificationHash: 'fcs-txt-007',
    fileSize: '16 KB',
    storyId: 'story-001',
    creatorPrice: 15000,
    enabledLicences: ['editorial', 'print', 'digital', 'broadcast'],
    exclusiveLock: null,
  },
  {
    id: 'asset-text-008',
    title: 'After the Fire: Huelva\'s Long Recovery',
    description: 'Follow-up on Huelva wildfire aftermath and recovery.',
    format: 'text',
    thumbnailUrl: null,
    textUrl: '/assets/texts/spain-wildfire-recovery.txt',
    textExcerpt: 'Six months after the fire that consumed forty-three thousand hectares of forest and agricultural land in western Huelva, the landscape remains a study in ash. Blackened trunks of cork oaks stand in rows like grave markers.',
    privacy: 'PUBLIC',
    declarationState: 'corroborated',
    publication: 'PUBLISHED',
    uploadedAt: '2026-03-02T09:00:00Z',
    certifiedAt: '2026-03-02T09:04:00Z',
    certificationHash: 'fcs-txt-008',
    fileSize: '12 KB',
    storyId: 'story-002',
    creatorPrice: 7000,
    enabledLicences: ['editorial', 'digital'],
    exclusiveLock: null,
  },
  {
    id: 'asset-text-009',
    title: 'Fault Lines: Istanbul\'s Earthquake Gamble',
    description: 'Investigation into Istanbul\'s earthquake preparedness.',
    format: 'text',
    thumbnailUrl: null,
    textUrl: '/assets/texts/istanbul-earthquake-prep.txt',
    textExcerpt: 'The seismograph at the Kandilli Observatory has not stopped recording micro-tremors for eleven days. Professor Mehmet Aydin watches the needle trace its jagged line across graph paper and does the arithmetic that keeps him awake at night.',
    privacy: 'PUBLIC',
    declarationState: 'fully_validated',
    publication: 'PUBLISHED',
    uploadedAt: '2026-02-28T15:00:00Z',
    certifiedAt: '2026-02-28T15:02:00Z',
    certificationHash: 'fcs-txt-009',
    fileSize: '14 KB',
    storyId: 'story-003',
    creatorPrice: 11000,
    enabledLicences: ['editorial', 'print', 'digital'],
    exclusiveLock: null,
  },
  {
    id: 'asset-text-010',
    title: 'Vanishing Ground: Tuvalu and the Rising Pacific',
    description: 'Dispatch from Tuvalu on rising sea levels and cultural preservation.',
    format: 'text',
    thumbnailUrl: null,
    textUrl: '/assets/texts/pacific-island-climate.txt',
    textExcerpt: 'At high tide, the ocean crosses the road. It happens twice a day now, a fact that the twelve thousand residents of Tuvalu have absorbed into their daily routines with the practised calm of people who have run out of room for alarm.',
    privacy: 'PUBLIC',
    declarationState: 'fully_validated',
    publication: 'PUBLISHED',
    uploadedAt: '2026-02-25T08:00:00Z',
    certifiedAt: '2026-02-25T08:03:00Z',
    certificationHash: 'fcs-txt-010',
    fileSize: '13 KB',
    storyId: 'story-001',
    creatorPrice: 9500,
    enabledLicences: ['editorial', 'print', 'digital'],
    exclusiveLock: null,
  },
  {
    id: 'asset-text-011',
    title: 'Priced Out of Home: Lisbon\'s Housing Affordability Collapse',
    description: 'Feature on the housing affordability crisis displacing residents from central Lisbon.',
    format: 'text',
    thumbnailUrl: null,
    textUrl: '/assets/texts/lisbon-housing-crisis.txt',
    textExcerpt: 'Ana Sousa is a schoolteacher in Lisbon. She has worked in the public education system for fourteen years, earning a salary that the government classifies as middle income.',
    privacy: 'PUBLIC',
    declarationState: 'fully_validated',
    publication: 'PUBLISHED',
    uploadedAt: '2026-03-15T08:00:00Z',
    certifiedAt: '2026-03-15T08:02:00Z',
    certificationHash: 'fcs-txt-011',
    fileSize: '13 KB',
    storyId: 'story-002',
    creatorPrice: 8500,
    enabledLicences: ['editorial', 'print', 'digital'],
    exclusiveLock: null,
  },
  {
    id: 'asset-text-012',
    title: 'The Silicon Shield: Taiwan\'s Semiconductor Industry and the Geometry of Power',
    description: 'Feature on how Taiwan\'s chip industry shapes global geopolitics.',
    format: 'text',
    thumbnailUrl: null,
    textUrl: '/assets/texts/taiwan-chip-sovereignty.txt',
    textExcerpt: 'Inside the sprawling campus of Taiwan Semiconductor Manufacturing Company in Hsinchu Science Park, the air in the fabrication halls is cleaner than an operating theatre.',
    privacy: 'PUBLIC',
    declarationState: 'fully_validated',
    publication: 'PUBLISHED',
    uploadedAt: '2026-02-01T10:00:00Z',
    certifiedAt: '2026-02-01T10:03:00Z',
    certificationHash: 'fcs-txt-012',
    fileSize: '14 KB',
    storyId: 'story-003',
    creatorPrice: 12000,
    enabledLicences: ['editorial', 'print', 'digital'],
    exclusiveLock: null,
  },
  {
    id: 'asset-text-013',
    title: 'After the Fire: Huelva\'s Long Road to Recovery',
    description: 'Report on recovery efforts in southern Spain months after devastating wildfires.',
    format: 'text',
    thumbnailUrl: null,
    textUrl: '/assets/texts/spain-wildfire-recovery.txt',
    textExcerpt: 'Eight months after the wildfire that consumed nearly 18,000 hectares of pine forest and scrubland in Huelva province, the landscape is still dominated by black.',
    privacy: 'PUBLIC',
    declarationState: 'fully_validated',
    publication: 'PUBLISHED',
    uploadedAt: '2025-11-22T12:00:00Z',
    certifiedAt: '2025-11-22T12:02:00Z',
    certificationHash: 'fcs-txt-013',
    fileSize: '13 KB',
    storyId: 'story-001',
    creatorPrice: 8000,
    enabledLicences: ['editorial', 'print', 'digital'],
    exclusiveLock: null,
  },
  {
    id: 'asset-text-014',
    title: 'The Fault Beneath the City: Istanbul\'s Unfinished Reckoning with Earthquake Risk',
    description: 'Investigation into Istanbul\'s earthquake preparedness and building safety failures.',
    format: 'text',
    thumbnailUrl: null,
    textUrl: '/assets/texts/istanbul-earthquake-prep.txt',
    textExcerpt: 'Seismologists no longer speak of whether a major earthquake will strike Istanbul. They speak only of when. The North Anatolian Fault runs directly beneath the Sea of Marmara.',
    privacy: 'PUBLIC',
    declarationState: 'fully_validated',
    publication: 'PUBLISHED',
    uploadedAt: '2025-10-28T08:00:00Z',
    certifiedAt: '2025-10-28T08:03:00Z',
    certificationHash: 'fcs-txt-014',
    fileSize: '13 KB',
    storyId: 'story-002',
    creatorPrice: 10000,
    enabledLicences: ['editorial', 'print', 'digital'],
    exclusiveLock: null,
  },
  {
    id: 'asset-text-015',
    title: 'Unfinished Peace: Colombia\'s Long Road From Accords to Reality',
    description: 'Feature on the gap between Colombia\'s peace accords and the reality on the ground.',
    format: 'text',
    thumbnailUrl: null,
    textUrl: '/assets/texts/colombia-peace-process.txt',
    textExcerpt: 'The former guerrilla fighter who now goes by the name Carlos tends a cacao nursery on a hillside that, a decade ago, was planted with coca.',
    privacy: 'PUBLIC',
    declarationState: 'fully_validated',
    publication: 'PUBLISHED',
    uploadedAt: '2026-02-28T14:00:00Z',
    certifiedAt: '2026-02-28T14:02:00Z',
    certificationHash: 'fcs-txt-015',
    fileSize: '15 KB',
    storyId: 'story-003',
    creatorPrice: 10500,
    enabledLicences: ['editorial', 'print', 'digital'],
    exclusiveLock: null,
  },
  {
    id: 'asset-text-016',
    title: 'The Melting Shortcut: Commerce, Conflict, and Climate on the Northern Sea Route',
    description: 'Feature on the geopolitical and environmental implications of Arctic shipping routes opening.',
    format: 'text',
    thumbnailUrl: null,
    textUrl: '/assets/texts/arctic-shipping-routes.txt',
    textExcerpt: 'The container ship Venta Maersk made its first transit of the Northern Sea Route in September 2018, sailing from Vladivostok to St. Petersburg in record time.',
    privacy: 'PUBLIC',
    declarationState: 'fully_validated',
    publication: 'PUBLISHED',
    uploadedAt: '2026-03-12T08:00:00Z',
    certifiedAt: '2026-03-12T08:02:00Z',
    certificationHash: 'fcs-txt-016',
    fileSize: '15 KB',
    storyId: 'story-001',
    creatorPrice: 11000,
    enabledLicences: ['editorial', 'print', 'digital'],
    exclusiveLock: null,
  },
  {
    id: 'asset-text-017',
    title: 'The Dam Between Nations: Egypt, Ethiopia, and the Battle for the Nile',
    description: 'Investigation into the geopolitical tensions over the Grand Ethiopian Renaissance Dam.',
    format: 'text',
    thumbnailUrl: null,
    textUrl: '/assets/texts/egypt-nile-dam.txt',
    textExcerpt: 'The fishermen on Lake Nasser launch their boats before dawn, as they have for decades, motoring past the immense bulk of the Aswan High Dam into waters that are measurably lower than a year ago.',
    privacy: 'PUBLIC',
    declarationState: 'fully_validated',
    publication: 'PUBLISHED',
    uploadedAt: '2026-02-05T11:00:00Z',
    certifiedAt: '2026-02-05T11:02:00Z',
    certificationHash: 'fcs-txt-017',
    fileSize: '14 KB',
    storyId: 'story-002',
    creatorPrice: 11500,
    enabledLicences: ['editorial', 'print', 'digital'],
    exclusiveLock: null,
  },
  {
    id: 'asset-text-018',
    title: 'Silenced: The War on Mexico\'s Press',
    description: 'Investigation into the dangers facing journalists in Mexico, the deadliest country for the press.',
    format: 'text',
    thumbnailUrl: null,
    textUrl: '/assets/texts/mexico-journalist-safety.txt',
    textExcerpt: 'The newsroom of El Debate, one of the oldest daily newspapers in the state of Sinaloa, is quieter than it should be on a Monday morning.',
    privacy: 'PUBLIC',
    declarationState: 'fully_validated',
    publication: 'PUBLISHED',
    uploadedAt: '2026-02-22T09:00:00Z',
    certifiedAt: '2026-02-22T09:03:00Z',
    certificationHash: 'fcs-txt-018',
    fileSize: '14 KB',
    storyId: 'story-003',
    creatorPrice: 12000,
    enabledLicences: ['editorial', 'print', 'digital'],
    exclusiveLock: null,
  },
  {
    id: 'asset-text-019',
    title: 'Stitched Together: Inside the Lives of Dhaka\'s Garment Workers',
    description: 'Feature on the daily lives and working conditions of garment workers in Bangladesh.',
    format: 'text',
    thumbnailUrl: null,
    textUrl: '/assets/texts/bangladesh-garment-workers.txt',
    textExcerpt: 'The alarm on Rehana Akhter\'s phone goes off at five in the morning, and by five-fifteen she is walking through the still-dark lanes of Mirpur.',
    privacy: 'PUBLIC',
    declarationState: 'fully_validated',
    publication: 'PUBLISHED',
    uploadedAt: '2026-03-25T12:00:00Z',
    certifiedAt: '2026-03-25T12:02:00Z',
    certificationHash: 'fcs-txt-019',
    fileSize: '17 KB',
    storyId: 'story-001',
    creatorPrice: 9500,
    enabledLicences: ['editorial', 'print', 'digital'],
    exclusiveLock: null,
  },
  {
    id: 'asset-text-020',
    title: 'Water Without End: Dispatches From Assam\'s Monsoon Catastrophe',
    description: 'Dispatches from Assam covering devastating monsoon floods and displacement.',
    format: 'text',
    thumbnailUrl: null,
    textUrl: '/assets/texts/india-monsoon-floods.txt',
    textExcerpt: 'The water arrived at Fatima Begum\'s house at three in the morning. She was asleep on a raised bamboo platform.',
    privacy: 'PRIVATE',
    declarationState: 'fully_validated',
    publication: 'PUBLISHED',
    uploadedAt: '2026-03-18T10:00:00Z',
    certifiedAt: '2026-03-18T10:02:00Z',
    certificationHash: 'fcs-txt-020',
    fileSize: '13 KB',
    storyId: 'story-002',
    creatorPrice: null,
    enabledLicences: [],
    exclusiveLock: null,
  },
]

// ── Stories ──

export const mockStories: Story[] = [
  {
    id: 'story-001',
    title: 'The Frontline of Climate Collapse',
    subtitle: 'How rising seas are redrawing the map of Southeast Asia',
    excerpt: 'From sinking villages in Indonesia to typhoon-battered coasts in the Philippines, the human cost of climate change is accelerating across the region.',
    privacy: 'PUBLIC',
    publication: 'PUBLISHED',
    publishedAt: '2026-03-20T10:00:00Z',
    contentMix: { photo: 8, video: 1, audio: 0, text: 0, illustration: 0, infographic: 1, vector: 1 },
    assetCount: 11,
    coverImageUrl: '/assets/8654_large.jpeg',
  },
  {
    id: 'story-002',
    title: "Inside Shenzhen's Silicon Shield",
    subtitle: 'The semiconductor war nobody is talking about',
    excerpt: "China's push for chip self-sufficiency is reshaping global supply chains. A ground-level look at the factories, workers, and geopolitics driving the shift.",
    privacy: 'PUBLIC',
    publication: 'PUBLISHED',
    publishedAt: '2026-03-18T14:00:00Z',
    contentMix: { photo: 1, video: 0, audio: 0, text: 1, illustration: 0, infographic: 0, vector: 0 },
    assetCount: 2,
    coverImageUrl: '/assets/12087_large.jpeg',
  },
  {
    id: 'story-003',
    title: 'Myanmar Border Crisis',
    subtitle: 'Displacement and survival at Mae Sot',
    excerpt: 'An ongoing documentation of the refugee crisis at the Thailand-Myanmar border.',
    privacy: 'PUBLIC',
    publication: 'DRAFT',
    publishedAt: null,
    contentMix: { photo: 6, video: 0, audio: 0, text: 0, illustration: 0, infographic: 0, vector: 0 },
    assetCount: 6,
    coverImageUrl: '/assets/13937_large.jpeg',
  },
]

// ── Articles ──

export const mockArticles: Article[] = [
  {
    id: 'article-001',
    title: 'The Quiet Drowning: Climate Migration in the Mekong Delta',
    excerpt: "As saltwater intrusion destroys farmland and rising tides swallow villages, millions of people in Vietnam's Mekong Delta are being forced to move.",
    articleType: 'creator_article',
    wordCount: 4200,
    publishState: 'published',
    publishedAt: '2026-03-19T09:00:00Z',
    assemblyVerified: true,
    sourceAssetCount: 8,
    certificationHash: 'fcs-art-a1b2c3',
    editorHandle: null,
    coverImageUrl: '/assets/10025_large.jpeg',
  },
  {
    id: 'article-002',
    title: 'Chip Wars: Ground Truth from Shenzhen',
    excerpt: 'Behind the geopolitical headlines about semiconductor sanctions, thousands of workers in Shenzhen are building the machines that will determine technological dominance for decades.',
    articleType: 'creator_article',
    wordCount: 3100,
    publishState: 'published',
    publishedAt: '2026-03-17T11:00:00Z',
    assemblyVerified: true,
    sourceAssetCount: 5,
    certificationHash: 'fcs-art-d4e5f6',
    editorHandle: null,
    coverImageUrl: '/assets/8939_large.jpeg',
  },
  {
    id: 'article-003',
    title: 'Press Freedom Under Pressure in Hong Kong',
    excerpt: 'A first-person account of reporting in Hong Kong as press freedoms continue to erode.',
    articleType: 'creator_article',
    wordCount: 2800,
    publishState: 'draft',
    publishedAt: null,
    assemblyVerified: false,
    sourceAssetCount: 3,
    certificationHash: null,
    editorHandle: null,
    coverImageUrl: '/assets/11862_large.jpeg',
  },
]

// ── Collections ──

export const mockCollections: Collection[] = [
  {
    id: 'coll-001',
    title: 'Climate & Environment',
    itemCount: 18,
    privacy: 'PUBLIC',
    thumbnails: [
      '/assets/8294_large.jpeg',
      '/assets/8654_large.jpeg',
      '/assets/10045_large.jpeg',
      '/assets/10025_large.jpeg',
    ],
  },
  {
    id: 'coll-002',
    title: 'Technology & Industry',
    itemCount: 11,
    privacy: 'PUBLIC',
    thumbnails: [
      '/assets/8939_large.jpeg',
      '/assets/12087_large.jpeg',
      '/assets/13977_large.jpeg',
      '/assets/2024_large.jpeg',
    ],
  },
]

// ── Certification Events ──

export const mockCertificationEvents: CertificationEvent[] = [
  {
    id: 'evt-001',
    type: 'upload',
    description: 'Uploaded "Refugee camp documentation, Mae Sot border"',
    timestamp: '2026-03-23T07:15:00Z',
    metadata: null,
  },
  {
    id: 'evt-002',
    type: 'fcs_layer_complete',
    description: 'FCS L1-L3 complete. Validation Declaration: Fully Validated. Hash: fcs-f3a6b9c2',
    timestamp: '2026-03-23T07:18:00Z',
    metadata: { declarationState: 'fully_validated', hash: 'fcs-f3a6b9c2' },
  },
  {
    id: 'evt-003',
    type: 'publication',
    description: 'Published "The Frontline of Climate Collapse" to Frontfolio',
    timestamp: '2026-03-20T10:00:00Z',
    metadata: null,
  },
  {
    id: 'evt-004',
    type: 'privacy_change',
    description: 'Set "Taiwan strait patrol" to RESTRICTED',
    timestamp: '2026-03-21T06:35:00Z',
    metadata: { assetId: 'asset-006', from: 'PUBLIC', to: 'RESTRICTED' },
  },
  {
    id: 'evt-005',
    type: 'fcs_layer_complete',
    description: 'FCS Layer 4 assembly certification. Article: fcs-art-a1b2c3',
    timestamp: '2026-03-19T09:05:00Z',
    metadata: { layer: 4, articleId: 'article-001' },
  },
  {
    id: 'evt-006',
    type: 'badge_change',
    description: 'Trust Badge assigned: Verified. Creator onboarding complete.',
    timestamp: '2026-03-15T10:30:00Z',
    metadata: { badge: 'verified' },
  },
]

// ── Buyer Account ──

export const mockBuyerAccount: BuyerAccount = {
  id: 'buyer-001',
  type: 'company',
  displayName: 'Maria Santos',
  email: 'maria@globalreport.news',
  companyName: 'Global Report Media',
  vatNumber: 'IE1234567T',
  state: 'active',
  role: 'content_commit_holder',
  lightboxes: [],
  savedSearchCount: 3,
}

// ── Lightbox ──

export const mockLightbox: Lightbox = {
  id: 'lb-001',
  name: 'Asia Coverage Q2',
  buyerId: 'buyer-001',
  assetIds: ['asset-001', 'asset-002', 'asset-004', 'asset-008'],
  createdAt: '2026-03-25T09:00:00Z',
  updatedAt: '2026-03-26T14:00:00Z',
}

// ── Transactions ──

export const mockTransactions: Transaction[] = [
  {
    id: 'txn-001',
    type: 'direct_catalogue',
    channel: 'direct',
    assetId: 'asset-001',
    buyerId: 'buyer-001',
    creatorId: 'sarahchen',
    licenceType: 'editorial',
    listedPrice: 15000,
    buyerPays: 18000,
    creatorReceives: 12000,
    platformEarns: 6000,
    completedAt: '2026-03-26T11:00:00Z',
    certifiedPackageId: 'pkg-001',
    settlementId: 'stl-001',
  },
]

// ── Settlements ──

export const mockSettlements: Settlement[] = [
  {
    id: 'stl-001',
    transactionId: 'txn-001',
    creatorId: 'sarahchen',
    amount: 12000,
    state: 'settled',
    route: 'sepa',
    queuedAt: '2026-03-26T11:00:00Z',
    settledAt: '2026-03-29T08:00:00Z',
    reference: 'SEPA-2026032901',
  },
]

// ── Social: Authors ──

export const socialAuthors: Record<string, CommentAuthor> = {
  sarahchen: {
    username: 'sarahchen',
    displayName: 'Sarah Chen',
    professionalTitle: 'Senior Correspondent, Asia Pacific',
    trustBadge: 'verified',
  },
  marcoricci: {
    username: 'marcoricci',
    displayName: 'Marco Ricci',
    professionalTitle: 'Photo Editor, European Bureau',
    trustBadge: 'verified',
  },
  ananyagupta: {
    username: 'ananyagupta',
    displayName: 'Ananya Gupta',
    professionalTitle: 'Investigative Reporter, South Asia',
    trustBadge: 'trusted',
  },
  jamesokafor: {
    username: 'jamesokafor',
    displayName: 'James Okafor',
    professionalTitle: 'Conflict Photographer',
    trustBadge: 'verified',
  },
  mariasantos: {
    username: 'mariasantos',
    displayName: 'Maria Santos',
    professionalTitle: 'Content Director, Global Report Media',
    trustBadge: null,
  },
}

// ── Social: Counts per content item ──

export const mockSocialCounts: Record<string, SocialCounts> = {
  'asset-001': { likes: 24, comments: 3, userLiked: false },
  'asset-002': { likes: 41, comments: 5, userLiked: true },
  'asset-004': { likes: 18, comments: 1, userLiked: false },
  'asset-005': { likes: 67, comments: 8, userLiked: true },
  'asset-006': { likes: 12, comments: 0, userLiked: false },
  'asset-008': { likes: 33, comments: 2, userLiked: false },
  'asset-011': { likes: 9, comments: 1, userLiked: false },
  'asset-013': { likes: 15, comments: 0, userLiked: false },
  'asset-019': { likes: 28, comments: 4, userLiked: true },
  'asset-025': { likes: 53, comments: 6, userLiked: false },
  'story-001': { likes: 89, comments: 7, userLiked: true },
  'story-002': { likes: 34, comments: 3, userLiked: false },
  'story-003': { likes: 22, comments: 2, userLiked: false },
  'article-001': { likes: 112, comments: 9, userLiked: true },
  'article-002': { likes: 45, comments: 4, userLiked: false },
  'article-003': { likes: 8, comments: 1, userLiked: false },
}

// ── Social: Comments ──

export const mockComments: Comment[] = [
  {
    id: 'cmt-001',
    targetType: 'story',
    targetId: 'story-001',
    author: socialAuthors.marcoricci,
    body: 'The aerial footage from Cebu adds significant context to the ground-level reporting. Strong visual sequencing throughout.',
    createdAt: '2026-03-21T08:30:00Z',
    parentId: null,
  },
  {
    id: 'cmt-002',
    targetType: 'story',
    targetId: 'story-001',
    author: socialAuthors.ananyagupta,
    body: 'Have you considered pairing this with the IPCC displacement data from last quarter? The Mekong Delta vector map could anchor a cross-regional comparison.',
    createdAt: '2026-03-21T11:15:00Z',
    parentId: null,
  },
  {
    id: 'cmt-003',
    targetType: 'story',
    targetId: 'story-001',
    author: socialAuthors.sarahchen,
    body: 'Good call. I have the IPCC dataset and a few supplementary infographics in draft. Will update the story package next week.',
    createdAt: '2026-03-21T14:00:00Z',
    parentId: 'cmt-002',
  },
  {
    id: 'cmt-004',
    targetType: 'article',
    targetId: 'article-001',
    author: socialAuthors.jamesokafor,
    body: 'This is essential reading. The on-the-ground detail from the Mekong Delta villages is something wire coverage consistently misses.',
    createdAt: '2026-03-20T09:00:00Z',
    parentId: null,
  },
  {
    id: 'cmt-005',
    targetType: 'article',
    targetId: 'article-001',
    author: socialAuthors.mariasantos,
    body: 'We licensed three assets from this package for our quarterly climate report. The provenance chain made editorial review straightforward.',
    createdAt: '2026-03-20T16:45:00Z',
    parentId: null,
  },
  {
    id: 'cmt-006',
    targetType: 'article',
    targetId: 'article-001',
    author: socialAuthors.marcoricci,
    body: 'The L4 assembly verification is a real differentiator. Knowing the source imagery is certified end-to-end changes how we can use it.',
    createdAt: '2026-03-21T10:00:00Z',
    parentId: null,
  },
  {
    id: 'cmt-007',
    targetType: 'asset',
    targetId: 'asset-001',
    author: socialAuthors.jamesokafor,
    body: 'Strong composition under difficult conditions. The depth of field isolates the action without losing the wider crowd context.',
    createdAt: '2026-03-17T12:00:00Z',
    parentId: null,
  },
  {
    id: 'cmt-008',
    targetType: 'asset',
    targetId: 'asset-002',
    author: socialAuthors.ananyagupta,
    body: 'The expression on Minister Li captures the tension perfectly. This frame will age well.',
    createdAt: '2026-03-18T09:30:00Z',
    parentId: null,
  },
  {
    id: 'cmt-009',
    targetType: 'asset',
    targetId: 'asset-002',
    author: socialAuthors.marcoricci,
    body: 'We used this alongside a panel shot from the same session. Excellent editorial pairing.',
    createdAt: '2026-03-18T14:00:00Z',
    parentId: null,
  },
  {
    id: 'cmt-010',
    targetType: 'story',
    targetId: 'story-003',
    author: socialAuthors.jamesokafor,
    body: 'Important documentation work. The situation at Mae Sot is badly underreported.',
    createdAt: '2026-03-24T08:00:00Z',
    parentId: null,
  },
]

// ── Social: Follow state for sarahchen ──

export const mockFollowState: FollowState = {
  followers: 247,
  following: 83,
  userFollows: false,
}

// ── Social: Conversations ──

export const mockConversations: Conversation[] = [
  {
    id: 'conv-001',
    participants: [socialAuthors.sarahchen, socialAuthors.mariasantos],
    lastMessage: {
      id: 'dm-003',
      conversationId: 'conv-001',
      sender: socialAuthors.mariasantos,
      body: 'We would like to discuss exclusive licensing for the climate collapse series. Can we set up a call this week?',
      createdAt: '2026-03-28T14:20:00Z',
      read: false,
    },
    unreadCount: 1,
    createdAt: '2026-03-27T10:00:00Z',
  },
  {
    id: 'conv-002',
    participants: [socialAuthors.sarahchen, socialAuthors.marcoricci],
    lastMessage: {
      id: 'dm-006',
      conversationId: 'conv-002',
      sender: socialAuthors.sarahchen,
      body: 'Thanks for the edit notes. I will reshoot the wide establishing shot next visit.',
      createdAt: '2026-03-26T09:15:00Z',
      read: true,
    },
    unreadCount: 0,
    createdAt: '2026-03-24T16:00:00Z',
  },
  {
    id: 'conv-003',
    participants: [socialAuthors.sarahchen, socialAuthors.ananyagupta],
    lastMessage: {
      id: 'dm-009',
      conversationId: 'conv-003',
      sender: socialAuthors.ananyagupta,
      body: 'The cross-border piece is looking strong. Let me know when you publish so I can reference it in mine.',
      createdAt: '2026-03-25T11:40:00Z',
      read: true,
    },
    unreadCount: 0,
    createdAt: '2026-03-22T08:30:00Z',
  },
]

export const mockMessages: DirectMessage[] = [
  {
    id: 'dm-001',
    conversationId: 'conv-001',
    sender: socialAuthors.sarahchen,
    body: 'Hi Maria. Thank you for your interest in the climate coverage. Happy to discuss terms.',
    createdAt: '2026-03-27T10:00:00Z',
    read: true,
  },
  {
    id: 'dm-002',
    conversationId: 'conv-001',
    sender: socialAuthors.mariasantos,
    body: 'Great. We are particularly interested in the Mekong Delta and Cebu packages. Our editorial team reviewed the provenance records and everything checks out.',
    createdAt: '2026-03-27T15:30:00Z',
    read: true,
  },
  {
    id: 'dm-003',
    conversationId: 'conv-001',
    sender: socialAuthors.mariasantos,
    body: 'We would like to discuss exclusive licensing for the climate collapse series. Can we set up a call this week?',
    createdAt: '2026-03-28T14:20:00Z',
    read: false,
  },
  {
    id: 'dm-004',
    conversationId: 'conv-002',
    sender: socialAuthors.marcoricci,
    body: 'Sarah, the protest sequence from Hong Kong is exceptional. A few notes on the crop for the lead image.',
    createdAt: '2026-03-24T16:00:00Z',
    read: true,
  },
  {
    id: 'dm-005',
    conversationId: 'conv-002',
    sender: socialAuthors.marcoricci,
    body: 'The tight crop on frame 3 loses the police line in the background. For editorial context, a wider crop would be stronger.',
    createdAt: '2026-03-25T08:45:00Z',
    read: true,
  },
  {
    id: 'dm-006',
    conversationId: 'conv-002',
    sender: socialAuthors.sarahchen,
    body: 'Thanks for the edit notes. I will reshoot the wide establishing shot next visit.',
    createdAt: '2026-03-26T09:15:00Z',
    read: true,
  },
  {
    id: 'dm-007',
    conversationId: 'conv-003',
    sender: socialAuthors.sarahchen,
    body: 'Ananya, are you still working on the South Asia displacement piece? I have some overlap from the Myanmar border.',
    createdAt: '2026-03-22T08:30:00Z',
    read: true,
  },
  {
    id: 'dm-008',
    conversationId: 'conv-003',
    sender: socialAuthors.ananyagupta,
    body: 'Yes, wrapping up field work next week. Would be valuable to cross-reference your Mae Sot documentation.',
    createdAt: '2026-03-23T14:00:00Z',
    read: true,
  },
  {
    id: 'dm-009',
    conversationId: 'conv-003',
    sender: socialAuthors.ananyagupta,
    body: 'The cross-border piece is looking strong. Let me know when you publish so I can reference it in mine.',
    createdAt: '2026-03-25T11:40:00Z',
    read: true,
  },
]
