'use client'

import { useState } from 'react'

/**
 * DEV-ONLY: Watermark Profile Approval Harness
 *
 * Visual review tool for the founder to approve, reject, or request
 * revision on the 6 draft watermark profiles before they become canonical.
 *
 * NOT wired to production. NOT activating baked watermarks.
 * Uses pre-rendered static images from public/dev/watermark-drafts/
 * generated by a bun script using the dormant processing module.
 */

const LEVELS = ['light', 'standard', 'heavy'] as const
type Level = (typeof LEVELS)[number]

const SAMPLES = [
  { key: 'dark-landscape', label: 'Dark Landscape', family: 'landscape' as const, desc: 'Very dark image — worst case for bar visibility' },
  { key: 'bright-landscape', label: 'Bright Landscape', family: 'landscape' as const, desc: 'Snow/white scene — tests bar contrast on light background' },
  { key: 'busy-people', label: 'Busy / People', family: 'landscape' as const, desc: 'Faces, hands, high detail — tests bar overlap with content' },
  { key: 'dark-portrait-face', label: 'Dark Portrait (Face)', family: 'portrait' as const, desc: 'Direct face-forward, dark background — portrait family' },
  { key: 'light-portrait-face', label: 'Light Portrait (Face)', family: 'portrait' as const, desc: 'High contrast portrait — tests bar readability on light areas' },
  { key: 'busy-portrait-street', label: 'Busy Portrait (Street)', family: 'portrait' as const, desc: 'Street scene with detail — tests attribution legibility' },
] as const

type Decision = 'pending' | 'approved' | 'rejected' | 'needs-revision'

interface ProfileDecision {
  level: Level
  family: 'portrait' | 'landscape'
  decision: Decision
  note: string
}

const LEVEL_LABELS: Record<Level, string> = {
  light: 'LIGHT — vertical bar, right edge, near top',
  standard: 'STANDARD — vertical bar, right edge, one-third from bottom',
  heavy: 'HEAVY — same vertical bar + scattered FF icons',
}

const LEVEL_PARAMS: Record<Level, Record<string, string>> = {
  light: {
    'Orientation': 'Vertical',
    'Width': '5.5% of short edge',
    'Position': 'Right edge, near top (2%)',
    'Scatter': 'None',
  },
  standard: {
    'Orientation': 'Vertical',
    'Width': '6.5% of short edge',
    'Position': 'Right edge, centered at one-third from bottom',
    'Scatter': 'None',
  },
  heavy: {
    'Orientation': 'Vertical (same bar as standard)',
    'Width': '6.5% of short edge',
    'Position': 'Right edge, centered at one-third from bottom',
    'Scatter': 'density=14, opacity=0.45, icon=40px',
  },
}

/** Static path to a pre-rendered watermark draft image. */
function draftUrl(sampleKey: string, level: Level) {
  return `/dev/watermark-drafts/${sampleKey}--${level}.jpg`
}

const DECISION_STYLES: Record<Decision, string> = {
  pending: 'border-yellow-400/30 bg-yellow-400/5',
  approved: 'border-green-500/40 bg-green-500/5',
  rejected: 'border-red-500/40 bg-red-500/5',
  'needs-revision': 'border-orange-400/40 bg-orange-400/5',
}

const DECISION_LABELS: Record<Decision, string> = {
  pending: 'PENDING',
  approved: 'APPROVED',
  rejected: 'REJECTED',
  'needs-revision': 'NEEDS REVISION',
}

export default function WatermarkApprovalPage() {
  const [decisions, setDecisions] = useState<ProfileDecision[]>(
    LEVELS.flatMap(level =>
      (['portrait', 'landscape'] as const).map(family => ({
        level, family, decision: 'pending' as Decision, note: '',
      })),
    ),
  )

  const [activeLevel, setActiveLevel] = useState<Level>('light')
  const [showParams, setShowParams] = useState(true)

  function updateDecision(level: Level, family: 'portrait' | 'landscape', decision: Decision) {
    setDecisions(prev => prev.map(d =>
      d.level === level && d.family === family ? { ...d, decision } : d,
    ))
  }

  function updateNote(level: Level, family: 'portrait' | 'landscape', note: string) {
    setDecisions(prev => prev.map(d =>
      d.level === level && d.family === family ? { ...d, note } : d,
    ))
  }

  function getDecision(level: Level, family: 'portrait' | 'landscape') {
    return decisions.find(d => d.level === level && d.family === family)!
  }

  const summary = {
    approved: decisions.filter(d => d.decision === 'approved').length,
    rejected: decisions.filter(d => d.decision === 'rejected').length,
    revision: decisions.filter(d => d.decision === 'needs-revision').length,
    pending: decisions.filter(d => d.decision === 'pending').length,
  }

  function exportDecisions() {
    const output = {
      exported_at: new Date().toISOString(),
      summary,
      decisions: decisions.map(d => ({
        profile: `${d.level}-${d.family}`,
        version: 1,
        decision: d.decision,
        note: d.note || null,
      })),
    }
    const blob = new Blob([JSON.stringify(output, null, 2)], { type: 'application/json' })
    const url = URL.createObjectURL(blob)
    const a = document.createElement('a')
    a.href = url
    a.download = `watermark-approval-${new Date().toISOString().slice(0, 10)}.json`
    a.click()
    URL.revokeObjectURL(url)
  }

  return (
    <div className="min-h-screen bg-neutral-950 text-white">
      {/* Header */}
      <div className="sticky top-0 z-50 bg-neutral-950/95 backdrop-blur border-b border-neutral-800 px-6 py-4">
        <div className="flex items-center justify-between max-w-[1800px] mx-auto">
          <div>
            <h1 className="text-lg font-bold tracking-tight">Watermark Profile Approval</h1>
            <p className="text-xs text-neutral-500 mt-0.5">
              DEV ONLY — Review artifacts. No production impact.
            </p>
          </div>
          <div className="flex items-center gap-4">
            <div className="flex gap-2 text-xs">
              <span className="text-green-400">{summary.approved} approved</span>
              <span className="text-red-400">{summary.rejected} rejected</span>
              <span className="text-orange-400">{summary.revision} revision</span>
              <span className="text-yellow-400">{summary.pending} pending</span>
            </div>
            <button
              onClick={exportDecisions}
              className="text-xs px-3 py-1.5 bg-neutral-800 hover:bg-neutral-700 border border-neutral-700 font-medium"
            >
              Export Decisions
            </button>
          </div>
        </div>
      </div>

      <div className="max-w-[1800px] mx-auto px-6 py-6">
        {/* Level tabs */}
        <div className="flex gap-1 mb-6">
          {LEVELS.map(level => (
            <button
              key={level}
              onClick={() => setActiveLevel(level)}
              className={`px-4 py-2 text-xs font-bold uppercase tracking-widest border ${
                activeLevel === level
                  ? 'bg-blue-600 border-blue-500 text-white'
                  : 'bg-neutral-900 border-neutral-800 text-neutral-400 hover:text-white'
              }`}
            >
              {level}
            </button>
          ))}
          <div className="flex-1" />
          <button
            onClick={() => setShowParams(!showParams)}
            className="px-3 py-2 text-xs text-neutral-500 hover:text-neutral-300 border border-neutral-800"
          >
            {showParams ? 'Hide' : 'Show'} Parameters
          </button>
        </div>

        {/* Level description + parameters */}
        <div className="mb-6 px-4 py-3 bg-neutral-900 border border-neutral-800">
          <p className="text-sm font-medium text-neutral-300">{LEVEL_LABELS[activeLevel]}</p>
          <p className="text-xs text-neutral-500 mt-1">Version 1 &middot; Status: DRAFT &middot; Not approved</p>
          {showParams && (
            <div className="mt-3 grid grid-cols-4 gap-3">
              {Object.entries(LEVEL_PARAMS[activeLevel]).map(([key, val]) => (
                <div key={key} className="text-xs">
                  <span className="text-neutral-500">{key}:</span>{' '}
                  <span className="text-neutral-300 font-mono">{val}</span>
                </div>
              ))}
            </div>
          )}
        </div>

        {/* Sample grid — 6 images x current level */}
        <div className="grid grid-cols-3 gap-4 mb-8">
          {SAMPLES.map(sample => {
            const d = getDecision(activeLevel, sample.family)
            return (
              <div key={sample.key} className={`border ${DECISION_STYLES[d.decision]} p-2`}>
                <div className="mb-2 flex items-center justify-between">
                  <div>
                    <span className="text-xs font-bold text-neutral-300">{sample.label}</span>
                    <span className="text-[10px] text-neutral-500 ml-2">{sample.family}</span>
                  </div>
                  <span className={`text-[10px] font-bold uppercase tracking-widest ${
                    d.decision === 'approved' ? 'text-green-400'
                      : d.decision === 'rejected' ? 'text-red-400'
                        : d.decision === 'needs-revision' ? 'text-orange-400'
                          : 'text-yellow-400'
                  }`}>
                    {DECISION_LABELS[d.decision]}
                  </span>
                </div>
                <img
                  src={draftUrl(sample.key, activeLevel)}
                  alt={`${activeLevel} ${sample.label}`}
                  className="w-full bg-neutral-900"
                  loading="lazy"
                />
                <p className="text-[10px] text-neutral-600 mt-1">{sample.desc}</p>
              </div>
            )
          })}
        </div>

        {/* Decision panel — one per family for active level */}
        <div className="grid grid-cols-2 gap-6 mb-12">
          {(['landscape', 'portrait'] as const).map(family => {
            const d = getDecision(activeLevel, family)
            return (
              <div key={family} className={`border p-4 ${DECISION_STYLES[d.decision]}`}>
                <h3 className="text-sm font-bold uppercase tracking-widest mb-3">
                  {activeLevel} &middot; {family}
                </h3>
                <div className="flex gap-2 mb-3">
                  {(['approved', 'needs-revision', 'rejected'] as const).map(action => (
                    <button
                      key={action}
                      onClick={() => updateDecision(activeLevel, family, action)}
                      className={`px-3 py-1.5 text-xs font-bold uppercase tracking-wider border ${
                        d.decision === action
                          ? action === 'approved' ? 'bg-green-600 border-green-500 text-white'
                            : action === 'rejected' ? 'bg-red-600 border-red-500 text-white'
                              : 'bg-orange-600 border-orange-500 text-white'
                          : 'bg-neutral-900 border-neutral-700 text-neutral-400 hover:text-white'
                      }`}
                    >
                      {action === 'needs-revision' ? 'Needs Revision' : action}
                    </button>
                  ))}
                  {d.decision !== 'pending' && (
                    <button
                      onClick={() => updateDecision(activeLevel, family, 'pending')}
                      className="px-2 py-1.5 text-[10px] text-neutral-600 hover:text-neutral-400"
                    >
                      Reset
                    </button>
                  )}
                </div>
                <textarea
                  value={d.note}
                  onChange={e => updateNote(activeLevel, family, e.target.value)}
                  placeholder="Notes (optional) — what to change, what works, what doesn't..."
                  className="w-full bg-neutral-900 border border-neutral-800 text-xs text-neutral-300 p-2 h-16 resize-none placeholder:text-neutral-700"
                />
              </div>
            )
          })}
        </div>

        {/* Cross-level comparison strip */}
        <div className="border-t border-neutral-800 pt-6 mb-8">
          <h2 className="text-sm font-bold uppercase tracking-widest text-neutral-400 mb-4">
            Cross-Level Comparison
          </h2>
          <p className="text-xs text-neutral-600 mb-4">
            Same image at all 3 intrusion levels, side by side.
          </p>
          {SAMPLES.slice(0, 4).map(sample => (
            <div key={sample.key} className="mb-6">
              <p className="text-xs font-bold text-neutral-400 mb-2">{sample.label}</p>
              <div className="grid grid-cols-3 gap-2">
                {LEVELS.map(level => (
                  <div key={level}>
                    <img
                      src={draftUrl(sample.key, level)}
                      alt={`${level} ${sample.label}`}
                      className="w-full bg-neutral-900"
                      loading="lazy"
                    />
                    <p className="text-[10px] text-neutral-600 text-center mt-1 font-bold uppercase">{level}</p>
                  </div>
                ))}
              </div>
            </div>
          ))}
        </div>

        {/* Footer */}
        <div className="border-t border-neutral-800 pt-4 pb-8 text-xs text-neutral-600">
          <p>All images are pre-rendered composites generated by the dormant processing module (bun script, not live).</p>
          <p>Profile version: 1. Approval status: DRAFT. No production delivery impact.</p>
          <p>Decisions are local to this session. Export to persist.</p>
        </div>
      </div>
    </div>
  )
}
