-- ════════════════════════════════════════════════════════════════
-- P5: Rename direct_offer_* DB objects to special_offer_*
--
-- Revision history
--   v1   (2026-04-18)  — Initial draft. Had semantic bug: §5 used
--                        ALTER FUNCTION RENAME, which left the
--                        RAISE EXCEPTION string literal still
--                        referencing direct_offer_events. Also had
--                        idempotency gap on §7/§8 (CREATE TRIGGER /
--                        CREATE POLICY without guards against
--                        re-run). Never applied. Never committed.
--                        Superseded before any DB activity.
--   v2   (2026-04-18)  — Fixed v1: §5 uses DROP FUNCTION + CREATE
--                        OR REPLACE with updated body text
--                        ('special_offer_events is append-only…');
--                        §7/§8 prepend DROP IF EXISTS of the new
--                        names; rollback block extended with
--                        matching idempotency (DO-wrapped ALTER
--                        TYPE + DROP-before-CREATE). Never applied.
--                        Superseded by v2.1 when the pre-apply
--                        introspection derivation surfaced 3
--                        implicit-named constraints that v2 did
--                        not rename.
--   v2.1 (2026-04-18)  — THIS VERSION, intended for apply. Adds:
--                          §6a — ALTER INDEX IF EXISTS × 2 renaming
--                                direct_offer_threads_pkey and
--                                direct_offer_events_pkey (PK
--                                constraint names auto-generated by
--                                Postgres from the inline `id uuid
--                                PRIMARY KEY …` declarations in
--                                20260408230006_direct_offer_tables
--                                .sql).
--                          §6b — DO-wrapped ALTER TABLE RENAME
--                                CONSTRAINT for
--                                direct_offer_events_thread_id_fkey
--                                (inline FK name auto-generated by
--                                Postgres from `thread_id … REFER-
--                                ENCES direct_offer_threads(id)`).
--                        ALTER TABLE ... RENAME TO does NOT rename
--                        associated constraint names, so these
--                        auto-named constraints require explicit
--                        renames for Gate E (post-apply intro-
--                        spection) to return 0 rows.
--                        Rollback block extended symmetrically:
--                        §6b reverse BEFORE §6a reverse BEFORE §6
--                        reverse (table-rename-back), because
--                        ALTER TABLE RENAME CONSTRAINT references
--                        the table and must run while the table
--                        still has its post-migration name.
--
-- Purpose
--   Phase 5 of the A.0 terminology lock (FEATURE_APPROVAL_ROADMAP.md
--   §A.0). Final rename pass for DB schema, following P1 (docs),
--   P2 (src/lib/ code module), P3 (/api routes), P4 (shared TS
--   types, schemas, user-visible UI copy). After this migration,
--   no direct_offer_* object remains in the public schema.
--
-- Scope — 14 unique DB objects renamed
--   Tables (2)
--     direct_offer_threads           → special_offer_threads
--     direct_offer_events            → special_offer_events
--
--   Enum types (3)
--     direct_offer_status            → special_offer_status
--     direct_offer_event_type        → special_offer_event_type
--     direct_offer_auto_cancel_reason → special_offer_auto_cancel_reason
--
--   Enum values (1)
--     licence_source_type value 'direct_offer' → 'special_offer'
--     (licence_grants.source_type / transactions.source_type rows
--     storing 'direct_offer' are migrated atomically by
--     ALTER TYPE RENAME VALUE.)
--
--   RLS policies (2 — drop + recreate with new names; bodies
--   preserved, one body re-texts the table reference)
--     direct_offer_threads_participant_read
--       → special_offer_threads_participant_read
--     direct_offer_events_participant_read
--       → special_offer_events_participant_read
--
--   Triggers (2 — drop + recreate with new names against
--   renamed table)
--     trg_direct_offer_events_no_update
--       → trg_special_offer_events_no_update
--     trg_direct_offer_events_no_delete
--       → trg_special_offer_events_no_delete
--
--   Functions (1 — drop + create with new name and updated body;
--   RAISE EXCEPTION literal rewritten to name the renamed table)
--     direct_offer_events_immutable()
--       → special_offer_events_immutable()
--
--   Implicit-named constraints (3 — auto-generated by Postgres
--   from inline PRIMARY KEY / REFERENCES in the original CREATE
--   TABLE statements; survive ALTER TABLE RENAME unless explicitly
--   renamed)
--     direct_offer_threads_pkey           → special_offer_threads_pkey
--       (PK constraint + its backing unique index share a name;
--       ALTER INDEX RENAME updates both atomically)
--     direct_offer_events_pkey            → special_offer_events_pkey
--       (same pattern)
--     direct_offer_events_thread_id_fkey  → special_offer_events_thread_id_fkey
--       (inline FK from direct_offer_events.thread_id →
--       direct_offer_threads(id); renamed via ALTER TABLE
--       RENAME CONSTRAINT)
--
-- Preserved as-is (reviewed and confirmed not in direct_offer_* namespace)
--   offer_checkout_intents (table)                  — generic prefix
--   offer_party, licence_type (enum types)          — generic prefix
--   idx_offer_threads_*, idx_offer_events_*,
--     idx_checkout_intents_buyer (indexes)          — generic prefix
--   fk_offer_threads_{buyer,creator,asset},
--     fk_checkout_intents_{buyer,creator,asset} (FKs)
--                                                   — generic prefix
--                                                     (explicitly
--                                                     named in
--                                                     the FK
--                                                     backfill
--                                                     migrations)
--   offer_checkout_intents_pkey,
--     offer_checkout_intents_thread_id_key,
--     offer_checkout_intents_thread_id_fkey         — generic
--                                                     prefix
--                                                     (auto-named
--                                                     but hosting
--                                                     table isn't
--                                                     being
--                                                     renamed)
--   CHECK constraints (offer_*, checkout_intent_*)  — generic prefix
--   Column names on all three tables                — generic names
--   offer_checkout_intents_participant_read policy  — neither name
--                                                     nor body
--                                                     mentions
--                                                     direct_offer
--
-- Pre-apply checklist
--   [ ] Remote-dev only; NOT prod.
--   [ ] Checkpoint tag `checkpoint/pre-special-offer-rename-20260418`
--       exists (pre-P2 state; rollback anchor).
--   [ ] Tests green at HEAD (P4 baseline: vitest 1080 passed / 1 skipped).
--   [ ] Pre-apply introspection queries (1.1–1.15 in the extended
--       P5 packet) run against remote-dev and match the derived
--       inventory: 18 rows, all schema=public.
--
-- Idempotency
--   - ALTER TABLE IF EXISTS, ALTER INDEX IF EXISTS (PG 15+)
--   - DROP POLICY / TRIGGER / FUNCTION IF EXISTS
--   - Enum type + enum value renames wrapped in DO blocks with
--     EXCEPTION clauses (no native IF EXISTS for those).
--   - ALTER TABLE … RENAME CONSTRAINT wrapped in a DO block with
--     an EXCEPTION handler (no native IF EXISTS for that sub-
--     command).
--   - Trigger + policy recreations: no IF NOT EXISTS in Postgres.
--     Belt-and-suspenders drop-before-create of the NEW names in
--     §7 and §8 (on top of the drops of the OLD names in §3/§4)
--     makes the whole migration safely re-runnable.
--   - Function replacement uses DROP + CREATE (not ALTER RENAME)
--     because the function body carries the old table name in a
--     RAISE EXCEPTION literal that must be rewritten.
--
-- Rollback (manual; SQL in comment block at end of file). The
-- checkpoint tag also lets git-level rollback to pre-P2 state if
-- the full 4-commit rename sequence needs unwinding. Rollback is
-- itself fully idempotent (same DO / IF EXISTS / drop-before-
-- create pattern as the forward migration). Rollback ordering is
-- symmetric to forward: §6b reverse precedes §6a reverse which
-- precedes §6 reverse, because ALTER TABLE RENAME CONSTRAINT
-- references the table by its current name.
-- ════════════════════════════════════════════════════════════════

BEGIN;


-- ┌─────────────────────────────────────────────────────────────┐
-- │  §1  Rename enum types                                      │
-- │                                                             │
-- │  Column definitions using these types reference them by     │
-- │  OID, so all status/event_type/auto_cancel_reason columns   │
-- │  follow the rename transparently.                           │
-- └─────────────────────────────────────────────────────────────┘

DO $$ BEGIN
  ALTER TYPE direct_offer_status RENAME TO special_offer_status;
EXCEPTION WHEN undefined_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TYPE direct_offer_event_type RENAME TO special_offer_event_type;
EXCEPTION WHEN undefined_object THEN NULL;
END $$;

DO $$ BEGIN
  ALTER TYPE direct_offer_auto_cancel_reason RENAME TO special_offer_auto_cancel_reason;
EXCEPTION WHEN undefined_object THEN NULL;
END $$;


-- ┌─────────────────────────────────────────────────────────────┐
-- │  §2  Rename the 'direct_offer' value on licence_source_type │
-- │                                                             │
-- │  licence_grants.source_type and transactions.source_type    │
-- │  rows currently storing 'direct_offer' are atomically       │
-- │  migrated to 'special_offer' by this statement — Postgres   │
-- │  stores enum values as OIDs, so no UPDATE is needed.        │
-- └─────────────────────────────────────────────────────────────┘

DO $$ BEGIN
  ALTER TYPE licence_source_type RENAME VALUE 'direct_offer' TO 'special_offer';
EXCEPTION WHEN invalid_parameter_value THEN NULL;
END $$;


-- ┌─────────────────────────────────────────────────────────────┐
-- │  §3  Drop RLS policies whose names reference direct_offer   │
-- │                                                             │
-- │  Policy bodies work via OID internally (they would continue │
-- │  to function against the renamed tables), but the policy    │
-- │  NAMES would be stale. Drop + recreate with new names in §8.│
-- │  offer_checkout_intents_participant_read is untouched — its │
-- │  name and body are independent of the direct_offer naming.  │
-- └─────────────────────────────────────────────────────────────┘

DROP POLICY IF EXISTS direct_offer_threads_participant_read
  ON direct_offer_threads;

DROP POLICY IF EXISTS direct_offer_events_participant_read
  ON direct_offer_events;


-- ┌─────────────────────────────────────────────────────────────┐
-- │  §4  Drop triggers that will be recreated in §7             │
-- │                                                             │
-- │  Triggers reference the function by name at CREATE time;    │
-- │  they must be dropped before §5 drops the function they     │
-- │  depend on.                                                 │
-- └─────────────────────────────────────────────────────────────┘

DROP TRIGGER IF EXISTS trg_direct_offer_events_no_update
  ON direct_offer_events;

DROP TRIGGER IF EXISTS trg_direct_offer_events_no_delete
  ON direct_offer_events;


-- ┌─────────────────────────────────────────────────────────────┐
-- │  §5  Replace the immutable-enforcement function             │
-- │                                                             │
-- │  The original function body contained a RAISE EXCEPTION     │
-- │  literal that named the old table:                          │
-- │    'direct_offer_events is append-only. …'                  │
-- │  A simple ALTER FUNCTION RENAME would leave that string     │
-- │  in place — user-visible and now stale. Drop + create       │
-- │  under the new name lets us rewrite the literal cleanly.    │
-- └─────────────────────────────────────────────────────────────┘

DROP FUNCTION IF EXISTS direct_offer_events_immutable();

CREATE OR REPLACE FUNCTION special_offer_events_immutable()
RETURNS TRIGGER AS $$
BEGIN
  RAISE EXCEPTION 'special_offer_events is append-only. % operations are forbidden.', TG_OP;
  RETURN NULL;
END;
$$ LANGUAGE plpgsql;


-- ┌─────────────────────────────────────────────────────────────┐
-- │  §6  Rename the tables                                      │
-- │                                                             │
-- │  Indexes, PKs, CHECK constraints, inline FKs, and FKs with  │
-- │  generic-prefix names (fk_offer_threads_*) all auto-follow  │
-- │  the table rename via OID references. Most of those objects │
-- │  also have names that do NOT contain "direct_offer", so     │
-- │  they need no explicit rename. The exceptions are the 3     │
-- │  auto-named constraints handled in §6a and §6b below.       │
-- └─────────────────────────────────────────────────────────────┘

ALTER TABLE IF EXISTS direct_offer_threads RENAME TO special_offer_threads;
ALTER TABLE IF EXISTS direct_offer_events  RENAME TO special_offer_events;


-- ┌─────────────────────────────────────────────────────────────┐
-- │  §6a Rename PK constraint names                             │
-- │                                                             │
-- │  PK constraints created by inline `id uuid PRIMARY KEY …`   │
-- │  in the original CREATE TABLE statements carry auto-names   │
-- │  `<table>_pkey`. ALTER TABLE … RENAME TO does NOT rename    │
-- │  associated constraint names, so the PKs are now attached   │
-- │  to the renamed tables but carry stale direct_offer_* names.│
-- │                                                             │
-- │  PK constraints share a name with their backing unique      │
-- │  index; ALTER INDEX RENAME updates both atomically.         │
-- └─────────────────────────────────────────────────────────────┘

ALTER INDEX IF EXISTS direct_offer_threads_pkey
  RENAME TO special_offer_threads_pkey;

ALTER INDEX IF EXISTS direct_offer_events_pkey
  RENAME TO special_offer_events_pkey;


-- ┌─────────────────────────────────────────────────────────────┐
-- │  §6b Rename the auto-named inline FK constraint             │
-- │                                                             │
-- │  The constraint was created implicitly by                   │
-- │    thread_id uuid NOT NULL REFERENCES direct_offer_threads… │
-- │  in the original direct_offer_events table definition.      │
-- │  Postgres names inline FKs `<table>_<column>_fkey`, so the  │
-- │  constraint is now attached to the renamed table            │
-- │  (special_offer_events) but carries the old name. Rename    │
-- │  explicitly.                                                │
-- │                                                             │
-- │  ALTER TABLE … RENAME CONSTRAINT has no native IF EXISTS;   │
-- │  wrap in a DO block with EXCEPTION handler for re-run       │
-- │  safety.                                                    │
-- └─────────────────────────────────────────────────────────────┘

DO $$ BEGIN
  ALTER TABLE special_offer_events
    RENAME CONSTRAINT direct_offer_events_thread_id_fkey
    TO special_offer_events_thread_id_fkey;
EXCEPTION WHEN undefined_object THEN NULL;
END $$;


-- ┌─────────────────────────────────────────────────────────────┐
-- │  §7  Recreate triggers on renamed table with new names      │
-- │                                                             │
-- │  Belt-and-suspenders drops of the NEW names make the        │
-- │  CREATE TRIGGER statements safe to re-run (Postgres has no  │
-- │  CREATE TRIGGER IF NOT EXISTS).                             │
-- └─────────────────────────────────────────────────────────────┘

DROP TRIGGER IF EXISTS trg_special_offer_events_no_update
  ON special_offer_events;

DROP TRIGGER IF EXISTS trg_special_offer_events_no_delete
  ON special_offer_events;

CREATE TRIGGER trg_special_offer_events_no_update
  BEFORE UPDATE ON special_offer_events
  FOR EACH ROW
  EXECUTE FUNCTION special_offer_events_immutable();

CREATE TRIGGER trg_special_offer_events_no_delete
  BEFORE DELETE ON special_offer_events
  FOR EACH ROW
  EXECUTE FUNCTION special_offer_events_immutable();


-- ┌─────────────────────────────────────────────────────────────┐
-- │  §8  Recreate RLS policies with new names                   │
-- │                                                             │
-- │  §8.1 body preserved byte-for-byte (no table name inside).  │
-- │  §8.2 body has the FROM clause re-texted to the new table   │
-- │       name (direct_offer_threads → special_offer_threads).  │
-- │       Semantics identical.                                  │
-- │                                                             │
-- │  Belt-and-suspenders drops of the NEW policy names make the │
-- │  CREATE POLICY statements safe to re-run (Postgres has no   │
-- │  CREATE POLICY IF NOT EXISTS).                              │
-- └─────────────────────────────────────────────────────────────┘

DROP POLICY IF EXISTS special_offer_threads_participant_read
  ON special_offer_threads;

DROP POLICY IF EXISTS special_offer_events_participant_read
  ON special_offer_events;

CREATE POLICY special_offer_threads_participant_read
  ON special_offer_threads
  FOR SELECT TO authenticated
  USING (
    buyer_id = auth.uid()
    OR creator_id = auth.uid()
  );

CREATE POLICY special_offer_events_participant_read
  ON special_offer_events
  FOR SELECT TO authenticated
  USING (EXISTS (
    SELECT 1 FROM special_offer_threads t
    WHERE t.id = special_offer_events.thread_id
      AND (t.buyer_id = auth.uid() OR t.creator_id = auth.uid())
  ));


-- ┌─────────────────────────────────────────────────────────────┐
-- │  §9  Update table-level COMMENTs that mentioned the old     │
-- │      "Direct Offer" prose (grep honesty at the schema       │
-- │      documentation layer). Column-level comments in the     │
-- │      original migrations describe functionality, not the    │
-- │      product name, and transfer unchanged via OID.          │
-- └─────────────────────────────────────────────────────────────┘

COMMENT ON TABLE special_offer_threads IS
  'Master Special Offer negotiation thread. One active thread per buyer × asset × licence. Spec §10.4.';

COMMENT ON TABLE special_offer_events IS
  'Append-only event log for Special Offer lifecycle. No UPDATE or DELETE permitted.';


COMMIT;


-- ════════════════════════════════════════════════════════════════
-- ROLLBACK (manual — commented, not executable)
--
-- Fully idempotent: same DO / IF EXISTS / drop-before-create
-- pattern as the forward migration, so the rollback can be run
-- more than once without errors.
--
-- Ordering: §6b reverse BEFORE §6a reverse BEFORE §6 reverse. The
-- FK constraint rename references the table by its current name
-- (special_offer_events), so it must run before the table is
-- renamed back to direct_offer_events. The PK index renames work
-- by OID and are order-insensitive relative to the table rename,
-- but are placed between §6b and §6 for a consistent progression
-- (special_offer_* → direct_offer_* from leaf constraints up to
-- the tables themselves).
--
-- BEGIN;
--
-- -- §9 reverse: restore original table comments
-- COMMENT ON TABLE special_offer_events IS
--   'Append-only event log for Direct Offer lifecycle. No UPDATE or DELETE permitted.';
-- COMMENT ON TABLE special_offer_threads IS
--   'Master Direct Offer negotiation thread. One active thread per buyer × asset × licence. Spec §10.4.';
--
-- -- §8 reverse: drop new-named policies
-- DROP POLICY IF EXISTS special_offer_events_participant_read ON special_offer_events;
-- DROP POLICY IF EXISTS special_offer_threads_participant_read ON special_offer_threads;
--
-- -- §7 reverse: drop new-named triggers
-- DROP TRIGGER IF EXISTS trg_special_offer_events_no_delete ON special_offer_events;
-- DROP TRIGGER IF EXISTS trg_special_offer_events_no_update ON special_offer_events;
--
-- -- §6b reverse: rename FK constraint back (BEFORE table rename-back,
-- -- because ALTER TABLE RENAME CONSTRAINT names the table)
-- DO $$ BEGIN
--   ALTER TABLE special_offer_events
--     RENAME CONSTRAINT special_offer_events_thread_id_fkey
--     TO direct_offer_events_thread_id_fkey;
-- EXCEPTION WHEN undefined_object THEN NULL;
-- END $$;
--
-- -- §6a reverse: rename PK indexes back (ALTER INDEX works by OID,
-- -- so order vs §6 is not strictly required, but placed here for
-- -- a consistent leaf-up progression)
-- ALTER INDEX IF EXISTS special_offer_events_pkey RENAME TO direct_offer_events_pkey;
-- ALTER INDEX IF EXISTS special_offer_threads_pkey RENAME TO direct_offer_threads_pkey;
--
-- -- §6 reverse: rename tables back
-- ALTER TABLE IF EXISTS special_offer_events  RENAME TO direct_offer_events;
-- ALTER TABLE IF EXISTS special_offer_threads RENAME TO direct_offer_threads;
--
-- -- §5 reverse: drop the special_offer_* named function + recreate
-- -- under the old name with the ORIGINAL error text.
-- DROP FUNCTION IF EXISTS special_offer_events_immutable();
--
-- CREATE OR REPLACE FUNCTION direct_offer_events_immutable()
-- RETURNS TRIGGER AS $$
-- BEGIN
--   RAISE EXCEPTION 'direct_offer_events is append-only. % operations are forbidden.', TG_OP;
--   RETURN NULL;
-- END;
-- $$ LANGUAGE plpgsql;
--
-- -- §7 forward (on restored-name table): recreate triggers under
-- -- restored names. Belt-and-suspenders drop-before-create since
-- -- CREATE TRIGGER has no IF NOT EXISTS.
-- DROP TRIGGER IF EXISTS trg_direct_offer_events_no_update ON direct_offer_events;
-- DROP TRIGGER IF EXISTS trg_direct_offer_events_no_delete ON direct_offer_events;
--
-- CREATE TRIGGER trg_direct_offer_events_no_update
--   BEFORE UPDATE ON direct_offer_events
--   FOR EACH ROW EXECUTE FUNCTION direct_offer_events_immutable();
-- CREATE TRIGGER trg_direct_offer_events_no_delete
--   BEFORE DELETE ON direct_offer_events
--   FOR EACH ROW EXECUTE FUNCTION direct_offer_events_immutable();
--
-- -- §8 forward (on restored-name tables): recreate policies under
-- -- restored names. Belt-and-suspenders drop-before-create since
-- -- CREATE POLICY has no IF NOT EXISTS.
-- DROP POLICY IF EXISTS direct_offer_threads_participant_read ON direct_offer_threads;
-- DROP POLICY IF EXISTS direct_offer_events_participant_read ON direct_offer_events;
--
-- CREATE POLICY direct_offer_threads_participant_read
--   ON direct_offer_threads
--   FOR SELECT TO authenticated
--   USING (buyer_id = auth.uid() OR creator_id = auth.uid());
--
-- CREATE POLICY direct_offer_events_participant_read
--   ON direct_offer_events
--   FOR SELECT TO authenticated
--   USING (EXISTS (
--     SELECT 1 FROM direct_offer_threads t
--     WHERE t.id = direct_offer_events.thread_id
--       AND (t.buyer_id = auth.uid() OR t.creator_id = auth.uid())
--   ));
--
-- -- §2 reverse: rename enum value back (DO-wrapped for re-run safety)
-- DO $$ BEGIN
--   ALTER TYPE licence_source_type RENAME VALUE 'special_offer' TO 'direct_offer';
-- EXCEPTION WHEN invalid_parameter_value THEN NULL;
-- END $$;
--
-- -- §1 reverse: rename enum types back (DO-wrapped × 3)
-- DO $$ BEGIN
--   ALTER TYPE special_offer_auto_cancel_reason RENAME TO direct_offer_auto_cancel_reason;
-- EXCEPTION WHEN undefined_object THEN NULL;
-- END $$;
--
-- DO $$ BEGIN
--   ALTER TYPE special_offer_event_type RENAME TO direct_offer_event_type;
-- EXCEPTION WHEN undefined_object THEN NULL;
-- END $$;
--
-- DO $$ BEGIN
--   ALTER TYPE special_offer_status RENAME TO direct_offer_status;
-- EXCEPTION WHEN undefined_object THEN NULL;
-- END $$;
--
-- COMMIT;
--
-- Alternative: git-level rollback to checkpoint/pre-special-offer-rename-20260418
-- and reset remote-dev via the rollback SQL above (or supabase db reset
-- if local-dev is recreated).
-- ════════════════════════════════════════════════════════════════
